another dono mask
NovaSector/NovaSector pull request #1182
Opened 2024-02-27 19:41 UTC by CandleJaxx

we do a little bit of gaming
![image](https://github.com/NovaSector/NovaSector/assets/68376391/0703297e-070d-4b80-9399-c5f712600f44)

(as far as im aware the dono hasn't gone through yet, but i'm uploading it earlier incase it needs edits)

2024-02-27 19:47 UTC, CandleJaxx commented
keep yourself safe

2024-02-28 20:21 UTC, GoldenAlpharex requested changes
Other than that, this will remain on hold until the donation happens.

2024-02-28 20:21 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +/obj/item/clothing/mask/gas/psycho_malice/proc/adjust_mask(mob/living/carbon/human/user)
Document this proc please.

2024-03-02 01:04 UTC, GoldenAlpharex approved these changes
Let's go!

2024-03-02 01:04 UTC, merged