Adds anosmia quirk
NovaSector/NovaSector pull request #1335
Opened 2024-03-08 07:17 UTC by NeonNik2245

## About The Pull Request

Adds quirk anosmia (0 points), that makes character don't feel any smells.

## How This Contributes To The Nova Sector Roleplay Experience
Now characters can have quirk and don't feel any smells of this world. For bad or good...

## Proof of Testing

![image](https://github.com/NovaSector/NovaSector/assets/106491639/6cb9e297-f524-4ef8-a3ad-3804bb06f565)

<details>
<summary>Screenshots/Videos</summary>
 
![image](https://github.com/NovaSector/NovaSector/assets/106491639/e7860980-9614-4cd5-b88e-c0a506e9b152)
![image](https://github.com/NovaSector/NovaSector/assets/106491639/584f5775-48e8-4d55-b55c-57b8ffc987d3)

</details>

## Changelog

:cl:
add: Adds anosmia quirk
/:cl:

2024-03-08 07:22 UTC, NeonNik2245 commented
My English is not very good, so I will gladly accept the wording changes, especially "smell the smells"

2024-03-08 08:08 UTC, NeonNik2245 commented
Aaand I don't know, why gateway_test failed on /datum/unit_test/spy_bounty 
> Error: No bounties were generated on first refresh for difficulty Hard
FAILURE #1: No bounties were generated on first refresh for difficulty Hard at code/modules/unit_tests/spies.dm:41

2024-03-08 21:39 UTC, SomeRandomOwl requested changes
Grammar pass, this wording makes a bit more sense

2024-03-08 21:39 UTC, SomeRandomOwl commented on code/datums/quirks/neutral_quirks/anosmia.dm
> +	medical_record_text = "Patient can't fell any smells."
```suggestion
/datum/quirk/item_quirk/anosmia
	name = "Anosmia"
	desc = "For some reasons you can't smell the smells."
	icon = FA_ICON_HEAD_SIDE_COUGH_SLASH
	value = 0
	mob_trait = TRAIT_ANOSMIA
	gain_text = span_notice("You suddenly notice the lack of smells, Your nose doesn't seem to work..")
	lose_text = span_danger("Your nose seemed to clear up, and you begin to smell things around you!")
	medical_record_text = "Patient lost the the sensation of smell."
```

2024-03-08 21:39 UTC, SomeRandomOwl commented on modular_nova/modules/pollution/code/pollution.dm
>  	var/list/singleton_cache = SSpollution.singletons
```suggestion
	if(HAS_TRAIT(sniffer, TRAIT_ANOSMIA)) //Anosmia holders can not smell things.
		return
	var/list/singleton_cache = SSpollution.singletons
```

2024-03-09 11:09 UTC, OrionTheFox commented on code/datums/quirks/neutral_quirks/anosmia.dm
> +	medical_record_text = "Patient can't fell any smells."
double period in gain_text 😭

2024-03-10 08:41 UTC, NeonNik2245 commented
> Transcendent Olfaction is also going to need to be affected by this. And Pheromone Receptors probably? Make those changes modular if it is possible.
> 
> Nothing else really comes to mind...but I may be missing some.
> 
> There are also various descriptions around that mention smell but you can ignore those as it would be too many edits for something cosmetic.

I also found forge, oven and deep frier smells, that's the most strange or hard to bypass, another is miasma in air, that gain you mood event, so it also has check for now

2024-03-10 09:07 UTC, NeonNik2245 commented
Can I add "Do not merge" by myself? Just wonder

2024-03-10 14:20 UTC, Iajret commented
> Can I add "Do not merge" by myself? Just wonder

as i said already, convert PR to draft while you change every smell to account for your quirk.

2024-03-24 18:27 UTC, NeonNik2245 commented
Make this quirk on upstream, so after that will change this pr

2024-03-28 20:59 UTC, RatFromTheJungle reviewed
grammar checks

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/datums/mutations/olfaction.dm
> +		to_chat(owner, span_warning("You can't feel any smells!"))
```suggestion
		to_chat(owner, span_warning("You can't smell anything anymore!"))
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/datums/mutations/olfaction.dm
> +	if(HAS_TRAIT(living_cast_on, TRAIT_ANOSMIA)) //Anosmia quirk holder cannot fell any smell
```suggestion
	if(HAS_TRAIT(living_cast_on, TRAIT_ANOSMIA)) // Anosmia quirk holders can't smell anything
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/datums/quirks/neutral_quirks/anosmia.dm
> +	desc = "For some reasons you can't smell the smells."
```suggestion
	desc = "For some reason, you can't smell anything.
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/datums/quirks/neutral_quirks/anosmia.dm
> +	gain_text = span_notice("You suddenly notice the lack of smells, Your nose doesn't seem to work.")
```suggestion
	gain_text = span_notice("You find yourself unable to smell anything!
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/datums/quirks/neutral_quirks/anosmia.dm
> +	lose_text = span_danger("Your nose seemed to clear up, and you begin to smell things around you!")
```suggestion
	lose_text = span_danger("Suddenly, you can smell again!!")
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/modules/antagonists/changeling/powers/pheromone_receptors.dm
> +		to_chat(user, span_warning("You can't feel any smells!"))
```suggestion
		to_chat(user, span_warning("You can't smell anything!"))
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/modules/antagonists/changeling/powers/pheromone_receptors.dm
> +	if(HAS_TRAIT(user, TRAIT_ANOSMIA)) //Anosmia quirk holder cannot feel any smell
```suggestion
	if(HAS_TRAIT(user, TRAIT_ANOSMIA)) //Anosmia quirk holders can't smell anything
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/modules/surgery/organs/internal/lungs/_lungs.dm
> +	if (HAS_TRAIT(breather, TRAIT_ANOSMIA)) //Anosmia quirk holder cannot feel miasma, but can take disease
```suggestion
	if (HAS_TRAIT(breather, TRAIT_ANOSMIA)) //Anosmia quirk holder cannot smell miasma, but can get diseases from it.
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on modular_nova/modules/mold/code/mold_disease.dm
> +				if(!HAS_TRAIT(affected_mob, TRAIT_ANOSMIA)) //Anosmia holders can't feel the smell, even if green smells strange
```suggestion
				if(!HAS_TRAIT(affected_mob, TRAIT_ANOSMIA)) //Anosmia holders can't smell this.
```

2024-03-28 20:59 UTC, RatFromTheJungle commented on code/datums/diseases/advance/symptoms/fire.dm
> +		if(HAS_TRAIT(living_mob, TRAIT_ANOSMIA)) //Anosmia quirk holder cannot fell any smell
```suggestion
		if(HAS_TRAIT(living_mob, TRAIT_ANOSMIA)) //Anosmia quirk holder can't smell anything.
```

2024-04-02 01:50 UTC, annikaRU commented
I'd gladly have "can't smell the smells" kinda funny

2024-04-09 19:29 UTC, NeonNik2245 commented
> See #1890 , I think this can be closed now?

Yes, thank you, I'll make PR to complete #1890 with perfumes and little more

2024-04-25 01:00 UTC, closed without merging