Add rich quirk (maybe balance needed)
NovaSector/NovaSector pull request #1337
Opened 2024-03-08 10:46 UTC by NeonNik2245

## About The Pull Request

Adds rich quirk (4 points)

![image](https://github.com/NovaSector/NovaSector/assets/106491639/ba1f00e6-7046-4254-993b-dd590410bf79)

This give you your very special credit card, it has random amount of credits at the shift start (now it's 1000-5000 credits)

![image](https://github.com/NovaSector/NovaSector/assets/106491639/006128a6-78e1-4101-9c09-885e9eb70e05)

You can freely transfer credits on and from your credit card.

## How This Contributes To The Nova Sector Roleplay Experience

People would be able to play rich characters

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/NovaSector/NovaSector/assets/106491639/221ff53e-b54b-48b5-8240-c43e45626ae9)  
</details>

## Changelog

:cl:
add: adds rich quirk and credit cards.
/:cl:

2024-03-08 21:43 UTC, SomeRandomOwl requested changes
Ok, I am not sure what i feel about this PR. I will have to have discussions about it. 

Regardless, grammar pass.

2024-03-08 21:43 UTC, SomeRandomOwl commented on code/datums/quirks/positive_quirks/rich.dm
> +	value = 4
```suggestion
/datum/quirk/item_quirk/rich
	name = "Rich"
	desc = "You have a lot of money. So much, that you take your credit card with you. Be sure you don't lose it."
	gain_text = span_danger("You feel come across a credit card on the floor!")
	lose_text = span_notice("You are bankrupt! Your credit card account has been closed.")
	medical_record_text = "Patient has a large amount of money."
	icon = FA_ICON_COINS
	value = 4
```

2024-03-08 21:56 UTC, CliffracerX commented on code/datums/quirks/positive_quirks/rich.dm
> +	value = 4
Should be "you come across", not "you feel come across"

2024-03-09 07:53 UTC, SomeRandomOwl commented on code/datums/quirks/positive_quirks/rich.dm
> +	value = 4
shush

2024-03-09 08:05 UTC, Ghommie commented
Make sure this is incompatible with indebted.

2024-03-10 07:02 UTC, NeonNik2245 commented
I can change amount of money (min and max) and make this quirk more expensive. I just need your help to determine those numbers

2024-03-10 07:19 UTC, NeonNik2245 commented
> Make sure this is incompatible with indebted, or not I guess.

Yeah, I'll add it

2024-03-10 14:41 UTC, NeonNik2245 commented
> > I can change amount of money (min and max) and make this quirk more expensive (like 8 points). I just need your help to determine those numbers
> 
> The problem is that we don't have quirk points. We turned them off! Downstreams might use them, still, and prices are relevant to them, but a quirk just goes into a slot irregardless. None of the other positive quirks barring arguably freerunner has a bombastic mechanical effect, unlike this.

We - NovaSector?

2024-03-24 05:46 UTC, GoldenAlpharex commented
After discussion, we're not really interested in this quirk, sorry.

2024-03-24 05:46 UTC, closed without merging