March 2024 iska's body markings
NovaSector/NovaSector pull request #1553
Opened 2024-03-21 01:06 UTC by iskawhiskers

## About The Pull Request

Adds the following body marking sprites:
![weight2_chest_m](https://i.imgur.com/PE47mvt.png)
![weight2_chest_f](https://i.imgur.com/YmW0D5u.png)
![blankface2_head](https://i.imgur.com/yGNPIsc.png)
![bigoleyes_head](https://i.imgur.com/QjGaLZV.png)
![monster2_head](https://i.imgur.com/rxn82sF.png)
![monster3_head](https://i.imgur.com/mTfoALA.png)

## How This Contributes To The Nova Sector Roleplay Experience

Sprites good

## Proof of Testing

![Image of character with monster3_head used](https://i.imgur.com/xyF6p8P.png)
Using monster3_head sprite
Tested on Bubberstation, but should work here too

## Changelog

:cl:
image: Added body marking sprites (monster2, monster3, weight2 (masc/fem variants), blankface2, bigoleyes)
/:cl:

2024-03-21 03:43 UTC, GoldenAlpharex requested changes
Could you include more screenshots featuring each marking individually? It's kinda hard to tell what's meant to be what.

2024-03-21 03:43 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm
> +	name = "Blank round face, Alt"
```suggestion
	name = "Blank Round Face, Alt"
```

2024-03-21 03:47 UTC, iskawhiskers commented
> Could you include more screenshots featuring each marking individually? It's kinda hard to tell what's meant to be what.

Not without compiling the entirety of the source code myself and that will take a ton of time with my terrible internet.  weight2 is just a greyscale version of the body weight body marking and monster2 is a recolourable and slightly better version of the monster mouth marking, though

2024-03-21 05:15 UTC, Nerev4r commented
![image](https://github.com/NovaSector/NovaSector/assets/12636964/337a2070-910e-418a-8e56-935952a65891)
grayscale bodyweight on an amab body

![image](https://github.com/NovaSector/NovaSector/assets/12636964/db4bb2d5-d1a3-498b-a4e1-08759cec1c8d)
on an afab body

![image](https://github.com/NovaSector/NovaSector/assets/12636964/8f5a7216-264a-474e-a704-bc8f1034ee46)
alt blank round face
![image](https://github.com/NovaSector/NovaSector/assets/12636964/c7862c57-5116-4fcf-bd2f-b9d06d5f5592)


![image](https://github.com/NovaSector/NovaSector/assets/12636964/6e2b7fad-d208-4c24-9707-772e8b4b6346)
as god intended
![image](https://github.com/NovaSector/NovaSector/assets/12636964/a9a6739d-e5fb-4970-b5c4-4b4af4ab2565)


![image](https://github.com/NovaSector/NovaSector/assets/12636964/d8bfc321-b430-4476-842c-ebbfb42ab3a9)
monster mouth included
![image](https://github.com/NovaSector/NovaSector/assets/12636964/6ee71336-fb66-4b14-9726-0b504a5dbcc5)


![image](https://github.com/NovaSector/NovaSector/assets/12636964/0f47849a-53b9-4fd0-88b8-441b15c3b0f9)
eye compatible version
![image](https://github.com/NovaSector/NovaSector/assets/12636964/c16742a2-5a2b-4db1-882a-bbbbed40f8fe)

![image](https://github.com/NovaSector/NovaSector/assets/12636964/57732105-9e2d-44fb-80de-aaa865ce8a52)
quit staring at me with them big ol eyes
![image](https://github.com/NovaSector/NovaSector/assets/12636964/730bdb55-8009-4199-95ec-8748e35a268f)

2024-03-21 05:21 UTC, Nerev4r commented
![image](https://github.com/NovaSector/NovaSector/assets/12636964/b6565f98-cd5c-4989-a63b-7f1f83685d28)
![image](https://github.com/NovaSector/NovaSector/assets/12636964/b62e7716-066c-4d23-8a5e-4735f8030497)
me when i

2024-03-21 05:32 UTC, iskawhiskers commented
Thank you based Juniper

2024-03-24 04:01 UTC, GoldenAlpharex approved these changes
Yeah, this seems fine to me, even if I know that characters without eyes will probably look weird with stuff likes glasses and the likes, but that's not like it's not already an issue with xenomorph hybrids and the likes.

2024-03-24 04:01 UTC, merged