[MODULAR] Adds a dice roll emote
NovaSector/NovaSector pull request #1556
Opened 2024-03-21 02:41 UTC by nikothedude

## About The Pull Request

Adapts and fixes up https://github.com/Citadel-Station-13/Citadel-Station-13-RP/pull/5008 to work on our codebase, as well as enhancing it a little to allow for negative bonuses

## How This Contributes To The Nova Sector Roleplay Experience

A lot of people, me included, like to roll dice to decide what happens to our c haracter. Dex saves, strength rolls, the likes. BUT. Its IMPOSSIBLE to tell if a roll is fudged or not, because all other people see is a PROMISE that you rolled high. No longer! You can no longer fudge your rolls and you are BOUND BY THEM.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
 
https://github.com/NovaSector/NovaSector/assets/59709059/5da226ae-dbe0-46a4-8f87-b37a2cae436a

</details>

## Changelog

:cl:
add: *dice, a emote that lets you roll dice

2024-03-21 02:41 UTC, nikothedude commented
This was made on a whim overnight and while it works its not perfect and WILL runtime if someone enters a incorrect string

2024-03-21 02:41 UTC, nikothedude commented
The runtime is harmless but I dont know how to filter them out prior to using roll()

2024-03-21 02:42 UTC, nikothedude commented
If maintainers desire, I will stop using roll() and switch to rand(), but thats extra effort and I dont think it matters too much

2024-03-21 02:42 UTC, nikothedude commented
WAIT WHY IS THAT ROLLING 13 GOD DAMN IT

2024-03-21 02:58 UTC, RatFromTheJungle commented on modular_nova/modules/roll_emote/code/roll_verb.dm
> +	var/message = "<b>[src]</b> rolls <b>[die_string]</b> for <b>[die_result]</b>"
i may just be misreading it, but it'd probably be good to use a funky rarely used span like his_grace or something to make it 'pop' a bit more in chat

2024-03-22 01:30 UTC, nikothedude commented on modular_nova/modules/roll_emote/code/roll_verb.dm
> +	var/message = "<b>[src]</b> rolls <b>[die_string]</b> for <b>[die_result]</b>"
green is more poppy

2024-03-24 04:09 UTC, GoldenAlpharex requested changes

2024-03-24 04:09 UTC, GoldenAlpharex commented on modular_nova/modules/roll_emote/code/roll_verb.dm
> +/atom/movable/proc/display_random_roll(param, show_errors = TRUE)
Document this please.

2024-03-24 04:09 UTC, GoldenAlpharex commented on modular_nova/modules/roll_emote/code/roll_verb.dm
> +	var/dc_number = text2num(copytext(dc, 3, length(dc) + 1))
This is so dense, it hurts my soul a little.

2024-03-24 04:32 UTC, nikothedude commented
ill see about addressing reviews tomorrow

2024-03-26 07:37 UTC, FlufflesTheDog commented on modular_nova/modules/roll_emote/code/roll_verb.dm
> +	Here is an example: D20-5/DC15. This will roll a twenty-sided die, subtract five and compare it against a difficulty check of 15.")
The provided example I believe runtimes on `roll` because the dice count is mandatory (`D20` -> `1D20`)

2024-03-26 08:02 UTC, FlufflesTheDog commented
I never realized how much I needed this in my life until trying it! Seems like it could be a ton of fun. It would be somewhat cool if you could optionally specify in the same emote what you're rolling for, but easy enough to follow that up in another emote as well.

2024-04-23 00:35 UTC, FlufflesTheDog commented
Blind people can't see the result of the emote

2024-05-07 19:54 UTC, nikothedude commented
> Just a reminder that this still has outstanding reviews, and several bugs have been reported.

oh i completely forget about this

honestly for as much as this pr adds, string parsing is absolutely in one of my weak sides and im a bit busy with projects rn

i might come back to this later but i just really suck ass at this kind of code, sorry

2024-05-07 19:54 UTC, closed without merging

2024-05-07 19:55 UTC, zeratino commented
over