[S][WIP] Silicon Infection Space threat
NovaSector/NovaSector pull request #1557
Opened 2024-03-21 03:14 UTC by Zergspower

## About The Pull Request

## How This Contributes To The Nova Sector Roleplay Experience

I've been having an idea in my mind for a couple years and never a real way to facilitate it, rebranding wireweed/hivemind/fleshmind into an infection form that can sit and loom over the station is a great jumping point for individual events as well as character lore.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
add: A variant of wireweed/hivemind/fleshmind to be isolated independent controllers
/:cl:

2024-03-24 03:40 UTC, GoldenAlpharex requested changes
I've only gone through the first eight files, this has already taken me over 20 minutes, I think it's going to be the same kind of comments for the rest of the files, so I'd just suggest combing through them and trying to follow that same logic to make it more readable, because at this pace, I'm here for another hour or two, and that won't be any fun.

2024-03-24 03:40 UTC, GoldenAlpharex commented on code/modules/unit_tests/simple_animal_freeze.dm
> +		/mob/living/simple_animal/hostile/fleshmind,
Ideally, we'll convert all of these to basic_mob instead, because otherwise we're just adding more technical debt here. I know you're already working on that, though, but I think it's a good idea to try and have that as soon as possible, so as to not forget it.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/Readme.md
> +Macleod962 - https://github.com/discordia-space/CEV-Eris/pull/2894 For Sprites and Sounds
That PR didn't have any sounds in it, please find the proper sources of those sounds, and ensure that they're actually fine to be used under our license (so, basically, that it's not stuff from other games or what have you).

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/_fleshmind_defines.dm
> +#define DOOR_OBJECT_LIST list(/obj/machinery/door/airlock, /obj/structure/door_assembly, /obj/machinery/door/firedoor, /obj/machinery/door/window)
```suggestion
#define DOOR_OBJECT_LIST list(\
	/obj/machinery/door/airlock, \
	/obj/structure/door_assembly, \
	/obj/machinery/door/firedoor, \
	/obj/machinery/door/window, \
)
```

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/_fleshmind_defines.dm
> +	"Pre-Release", "Commercial Release", "Closed Alpha", "Hivebuilt")
```suggestion
#define AI_SURNAME_LIST list( \
	"Mk I", \
	"Mk II", \
	"Mk III", \
	"Mk IV", \
	"Mk V", \
	"Mk VI", \
	"Mk VII", \
	"Mk VIII", \
	"Mk IX", \
	"Mk X", \
	"Mk XI", \
	"Mk XII", \
	"Mk XIII", \
	"Mk XIV", \
	"v0.9", \
	"v1.0", \
	"v1.1", \
	"v2.0", \
	"2418-B", \
	"Activated Shard", \
	"Pre-Release", \
	"Commercial Release", \
	"Closed Alpha", \
	"Hivebuilt", \
)
```

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/_fleshmind_defines.dm
> +#define FLESHCORE_NEXT_CORE_DAMAGE_WIREWEED_ACTIVATION_COOLDOWN 10 SECONDS // The amount of time until we can activate nearby wireweed again.
I'm not going to do all of them, but please do autodoc comments like these for all of the defines. It makes it so much easier in the future when maintaining this stuff.
```suggestion
/// How much progress is required to spread?
#define FLESHCORE_SPREAD_PROGRESS_REQUIRED 200
/// How many times do we need to spread until we can create a new structure?
#define FLESHCORE_SPREADS_FOR_STRUCTURE 50
/// Upon creation, how many times do we spread instantly?
#define FLESHCORE_INITIAL_EXPANSION_SPREADS 30
/// Upon creation, how many structures do we spawn instantly?
#define FLESHCORE_INITIAL_EXPANSION_STRUCTURES 5
/// Every subsystem fire, how much progress do we gain?
#define FLESHCORE_SPREAD_PROGRESS_PER_SUBSYSTEM_FIRE 40
/// The baseline of the above.
#define FLESHCORE_BASE_SPREAD_PROGRESS_PER_SUBSYSTEM_FIRE 40
/// How likely (%) are we to attack every SS fire?
#define FLESHCORE_ATTACK_PROB 20
/// How likely (%) are we to spawn a wall to seal a gap every SS fire?
#define FLESHCORE_WALL_PROB 30
/// The amount of time until we can activate nearby wireweed again.
#define FLESHCORE_NEXT_CORE_DAMAGE_WIREWEED_ACTIVATION_COOLDOWN 10 SECONDS
```

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +	var/list/structure_types = list(
Can this ever change? Because if not, might as well add `static/` after `var/`

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +	return
```suggestion
	if(!do_initial_expansion)
		return
	
	initial_expansion()
```

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/register_new_asset(obj/structure/fleshmind/new_asset)
Document this proc please.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/initial_expansion()
Document this proc please.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/wireweed_process(do_spread, do_attack, progress_structure = TRUE)
This proc is giving me a headache just glancing over it, could you try and see about splitting it into multiple procs, so that it's more easily readable?

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/spawn_new_core()
Document this.
Also, I feel like this is almost the same code as in the `New()`, surely that means it's possible to turn at least parts of this into a proc to save on some code duplication.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +			if(LAZYLEN(possible_transfer_points)) // OH SHIT IM FEELING IT
```suggestion

			if(LAZYLEN(possible_transfer_points)) // OH SHIT IM FEELING IT
```

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +					continue
This should probably all be made into one proc that you check in a single `if()`, to make this code more readable. This is all giving me a headache, there's faaaar too much stuff going on and being done into this one proc as well.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/spawn_structure(turf/location, structure_type)
Why do all the others return the spawned thing, except this one?

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +		spawn_structure(location, structure_to_spawn)
Try to let your code breathe, I'm seeing a block of code like this one and I'm starting to choke. It's very hard to read.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/wireweed_death(obj/structure/fleshmind/dying_wireweed, force)
Please document this.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/// When a core is destroyed.
Proc documentation should say what it's intended to do, not what it's called by, as that's not very informative.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +	activate_wireweed_nearby(get_turf(dying_structure), GENERAL_DAMAGE_WIREWEED_ACTIVATION_RANGE)
Same thing here. Or at least, make it a complete sentence.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/component_death(datum/component/machine_corruption/deleting_component, force)
Document this please.

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +	qdel(src)
See how much more easily it can be read now?
```suggestion
	for(var/obj/structure/fleshmind/structure/structure_thing as anything in controlled_structures)
		qdel(structure_thing)

	for(var/obj/structure/fleshmind/structure/wireweed_wall/wall_thing as anything in controlled_walls)
		qdel(wall_thing)

	for(var/datum/component/machine_corruption/corruption_thing as anything in controlled_machine_components)
		qdel(corruption_thing)

	if(just_structures)
		return

	for(var/obj/structure/fleshmind/wireweed/wireweed_thing as anything in controlled_wireweed)
		qdel(wireweed_thing)

	for(var/obj/structure/fleshmind/structure/core/core_to_destroy as anything in cores)
		qdel(core_to_destroy)

	qdel(src)
```

2024-03-24 03:40 UTC, GoldenAlpharex commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_environment_objects.dm
> +/obj/structure/fleshmind/wireweed/proc/on_entered(datum/source, atom/movable/moving_atom)
Document these please.

2024-03-25 14:45 UTC, Zergspower commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +	var/list/structure_types = list(
Not unless one is added in the future

2024-03-25 14:52 UTC, Zergspower commented on modular_nova/modules/space_ruin_specifics/code/Readme.md
> +Macleod962 - https://github.com/discordia-space/CEV-Eris/pull/2894 For Sprites and Sounds
Looks like they called their already existing sounds - however i spent a while trying to find the second set and i think they come from SS2. Going to remove those since while the game's 30 years old i couldnt see anything about it being public domain yet.

2024-03-25 17:39 UTC, Zergspower commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/spawn_new_core()
This one's the 'tumor' structure that will generate if enough wireweed forms, the other core one is for the initial primary core

2024-03-26 13:31 UTC, Zergspower commented on modular_nova/modules/space_ruin_specifics/code/fleshmind_controller.dm
> +/datum/fleshmind_controller/proc/wireweed_process(do_spread, do_attack, progress_structure = TRUE)
> This proc is giving me a headache just glancing over it, could you try and see about splitting it into multiple procs, so that it's more easily readable?

I'm not sure how actually - i split it apart to maybe help?

2025-04-08 23:47 UTC, closed without merging