[MODULAR] Expands character customization by adding all species limbs to the augments tab.
NovaSector/NovaSector pull request #1643
Opened 2024-03-26 20:35 UTC by Iamgoofball

## About The Pull Request
![CPrhPpTrWL](https://github.com/NovaSector/NovaSector/assets/4081722/46e57ef5-29e4-4816-8d56-072623916e4d)

Expands character customization by adding all species limbs to the augments tab.

## How This Contributes To The Nova Sector Roleplay Experience

This is something that was on my todo list during the new character customization menu but I scrapped it for time because head/chest augments didn't work at the time.

This expands character customization to allow you to use the full assortment of limb options we've got for species without being locked into a specific set of limbs. Wanna have a kickass skeleton arm on your right hand but a rock golem arm on your left? Go for it.

This will let you gamers cut back on the volume of species that exist just to change the sprites as people can just assemble it 

Can probably put the unique species organs in the organ augs pool too, but that'd require some additional boilerplate to ensure you get nitrogen/plasma tanks if you took vox/plasmaman lungs.

## Proof of Testing
![shEDUXkhgb](https://github.com/NovaSector/NovaSector/assets/4081722/d0fc5239-5154-4ae0-8da3-2ca207c540a5)
he walks the station

## Changelog

:cl:
add: Expands character customization by adding all species limbs to the augments tab.
/:cl:

2024-03-26 20:38 UTC, CliffracerX commented
🙏
Goof, I owe you one.  (Possibly the boilerplate to fix up internals tank selection with organs, bc if you add that then slugcat eyes can be available through the menu too.)

2024-03-27 17:47 UTC, GoldenAlpharex commented
I'll be handling this one, since it's a pretty big deal, but I'm very busy with Uni at the moment, so I should be able to get around to this in about a month. It might be sooner, but I don't want to make promises I can't hold.

2024-03-29 15:17 UTC, Iamgoofball commented
The fix does literally nothing outside of this PR since there's no greyscale limbs in the augs menu at this time

2024-04-06 17:56 UTC, Iamgoofball commented
stale-b-gone

2024-04-14 05:13 UTC, Iamgoofball commented
stale-b-gone

2024-05-06 19:20 UTC, GoldenAlpharex requested changes
I'm still not 100% sure how well this'll go, but for sure, these changes need to be made first, before this can be test-merged.

2024-05-06 19:20 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/client/augment/limbs.dm
> +				old_limb.set_icon_greyscale(UNLINT(initial(new_limb.icon_greyscale))) // stupid var_protected memes
We don't have a getter for this? If we don't, then we should probably just make a getter proc for it instead.

2024-05-06 19:20 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
> +	uses_greyscale = TRUE
I think it would be better to leave ghouls out of this for the time being, mainly because they have special logic that would make it a total pain when those limbs come off of a non-ghoul.

2024-05-06 19:20 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
> +	uses_robotic_styles = FALSE
If you're going to list out everything like this in one file, try to at least keep a consistent pattern, such as head, chest, left arm, right arm, left leg, right leg, like you were doing before. Just going kinda random half of the time just makes this a lot harder to review, and makes it harder to read in general (because you have to pay more attention due to the patterns constantly changing).

2024-05-06 19:20 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
> +	uses_robotic_styles = FALSE
I don't think that skeleton limbs should be included here. Skeletons aren't a roundstart species, and aren't really covered, or planned to be covered, by lore as it stands, as far as I'm aware.

2024-05-06 19:20 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
> +	uses_robotic_styles = FALSE
Abductors are antags, you shouldn't have the ability to look like a species that's only ever used for antagonism, please remove this from being an option.

2024-05-06 19:20 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
Human arms also don't seem to have been included in this, I assume that was probably an oversight.

2024-05-06 23:20 UTC, Iamgoofball commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
> +	uses_robotic_styles = FALSE
Don't you guys have greys turned on in config as a playable? I might be misremembering; I'll shut them off otherwise.

2024-05-06 23:20 UTC, Iamgoofball commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
lmao yeah i forgot those

2024-05-15 07:39 UTC, Iamgoofball commented
You'd need to carve up sock rendering into right/left and that'd add a lot of layering overhead

2024-05-26 01:14 UTC, CliffracerX commented
Needs an update for slime limbs, path has changed from /limbtype/slime/roundstart to /limbtype/jelly/slime/roundstart @Iamgoofball

2024-05-26 18:33 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/client/augment/species_limbs.dm
> +	uses_robotic_styles = FALSE
Nope, we don't have them as playable.

2024-06-23 07:00 UTC, Iamgoofball commented
@CliffracerX got it, thanks

2024-07-25 20:31 UTC, GoldenAlpharex commented
It's been picked up by https://github.com/NovaSector/NovaSector/pull/3738, so I'll just close this one.

2024-07-25 20:31 UTC, closed without merging

2024-07-26 03:18 UTC, Iamgoofball commented
@GoldenAlpharex yeah just make sure i'm in the changelog