[MODULAR] Removes the vetlock from pet owner and shapeshifter
NovaSector/NovaSector pull request #1816
Opened 2024-04-05 01:04 UTC by nikothedude

## About The Pull Request

Title.

## How This Contributes To The Nova Sector Roleplay Experience

Shapeshifter was arbitrarily vetlocked as it was "designed as a veteran quirk" in https://github.com/NovaSector/NovaSector/pull/1065, and pet owner was vetlocked out of paranoia in https://github.com/Skyrat-SS13/Skyrat-tg/pull/25142. 

Firstly, I havent actually seen an argument as to why shapeshifter is vetlocked, so let me rebutt a few arguments that I think might crop up.

1. "People will use it to make weird looking characters" - already doable in char creation
2. "People will use it to hide their identities" - Already doable via shapeshift disk and slimepeople (One of which is undetectable and unpredictable, you can go "oh that slime person will look different" with slimes, not with shapechanger NIF or quirk)
3. "It serves as a incentive to be a veteran" - Absolutely horrible justification. From what I understand, veteran exists as a way to give people access to funkier things that we might not be able to trust the general playerbase with (ex. why clown is vetlocked) - Things should not be vetlocked arbitrarily to get people to be veteran, and I can easily make counterarguments such as, it _also_ clogs the application process more, or, more importantly, _deprives people of fun mechanics_ they _can_ be trusted with just because they didnt _apply_. Being a vet should be a status of _trust_, not a status of _"heightened citizenship"_.

As for pet owner, the PR author themselves said they arent too attached to it being a pet owner. Let me break down some arguments for its vet locking and say why theyre false.
1. "Veteran incentive" - See above
2. "People will spam pets and flood the interlink" - Do you see people en masse getting skub and just flooding the interlink with it? Do you see people flooding the station with monkeys _en masse_? People do this, yes, but the keyword is en masse, as thats when it gets really disruptive. SOME people might just drop their pets for no reason, but certainly not the entire playerbase - they arent a dedicated grief machine.
3. "Some pets like horses can be overpowered" - If the animal is mountable, we can compromise by vetlocking those animals only 
4. "Some pets like horses are _stupid_" - See above, I agree but I also think it isnt an issue since people wouldnt be doing it en masse

For 2 and 4 unfortunately I cant conclusively prove myself right as the only way to do so is to test. Doubly unfortunately, this isnt exactly the PR that would get conclusive results on a TM, its one of those long term issues.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
localhost lets you take all quirks so i cant lmao

</details>

## Changelog

:cl:
add: Shapeshifter is no longer vetlocked
add: Pet owner is no longer v etlocked
/:cl:

2024-04-05 01:05 UTC, nikothedude commented
not a removal but go off label bot

2024-04-05 01:05 UTC, nikothedude commented
wait its literally a removal

2024-04-05 01:07 UTC, nikothedude commented
im not touching oversized since i kinda forgot why its vetlocked

2024-04-05 01:34 UTC, nikothedude commented
By the way, if the intent of vetlocking shapeshifter is to not step on the toes of the NIF, it just shouldnt exist honestly. Vetlocking does _not solve that problem_

2024-04-05 04:40 UTC, nikothedude commented
> doesnt the nif shapeshifter just do really basic stuff like hairstyle and etc?

last i used it i had control over everything

2024-04-05 18:04 UTC, nikothedude commented
i have been informed shapeshifter was designed as a vet quirk by a commissioner, therfore it was arbitrarily locked

2024-04-08 03:10 UTC, GoldenAlpharex requested changes
In general, I don't think a quirk shouldn't remain vet-locked just because you don't like that there's vet-locked quirks to begin with. I disagree with the sentiment that we shouldn't have rewards for Veterans to begin with, since they're meant to be people we trust, and watering down the reasons to have such a system just removes the incentive for people to genuinely try harder at being good players. I know it might sound strange at first, but if they've not really got much reason to put themselves up to a higher standard, why would they bother?

Veteran quirks are by design meant to not be something _everyone_ has access to, because we generally don't want to see a large portion of the station rocking them. Of course, some of them also come with advantages that we don't want to see people abuse, and couldn't trust the playerbase at large with, because we just _know_ people would abuse them, but it's not the _only_ reason behind them.

2024-04-08 03:10 UTC, GoldenAlpharex commented on modular_nova/modules/pet_owner/pet_owner.dm
I'm against this, primarily because I don't want to see more people carrying pets on themselves. People might see it as cute, but when you start getting multiple people in a room with cats and mice and whatever in their backpacks making all kinds of noises, it starts getting really disruptive to the flow of roleplay, by being a big source of distraction and clogging up the chat. I also see it as an IC reward for trusted employees, I don't think we want to turn the station into a zoo every shift, because half of the crew brings in whatever pet they've got at home.

2024-04-09 01:41 UTC, nikothedude commented on modular_nova/modules/pet_owner/pet_owner.dm
since this argument is based on a possibility, i dont really know how to disprove this other than saying that i _feel_ like most people wont bring in a pet, just like how people dont go around throwing random stuff everywhere for no reason

i take it this is a no on removing the vetlock for both the quirks?

2024-04-11 17:23 UTC, YehnBeep commented on modular_nova/modules/pet_owner/pet_owner.dm
> since this argument is based on a possibility, i dont really know how to disprove this other than saying that i feel like most people wont bring in a pet

I play on a server where absolutely everyone can have a pet, and the vast majority of people don't bother.

That said new cats are much spammier than old cats. (And I miss the "Esp!" they used to make). Maybe they could be made less chatty, as they were before the rework..?

2024-04-12 11:52 UTC, Ketrai commented
For slime shapeshifting you still have to be a slime. Doesn't the regular shapeshifter let you turn into animals and other stuff as well? I can see that one requiring some trust for sure. Especially with how weird/confusing it can be to see an animal walk into an area, and then you find them to be a person when you didn't expect them.

2024-04-12 12:01 UTC, Ketrai commented on modular_nova/modules/pet_owner/pet_owner.dm
Considering pet owner costs several points and it's not even restricted on skyrat, where I honestly don't see people flooding the station with pets, ever. If there's ever any doubt simply testmerge it and observe a couple rounds. 

Also, pets can be a nice conversation starter, I see them more likely to be encouraging roleplay rather than disrupt it. People don't tend to make a big deal out of the bartender putting 6 cats in the bar or something. Most pets have their talk interval set to like 10, which means they often go long strides without saying a single thing. The stronger tools against chat flooding are present.

- Find a secluded area.
- Turn off commons on the radio, if people need you, they can PDA if you don't respond on commons.
- Hi-light text with the chat feature allowing you to do so, letting you keep track of your conversation partner even in crowded areas.

2024-05-06 00:50 UTC, closed without merging

2024-07-18 04:32 UTC, Floofies commented
@GoldenAlpharex @nikothedude

I am stating this once and for posterity here: I was **paid money** to create that quirk according to a specific scope-of-work, which included restricting it to veterans. Nothing I did was arbitrary or according to any argument anyone has made.