Adds department guard belts + equipment qol
NovaSector/NovaSector pull request #1928
Opened 2024-04-11 19:54 UTC by honkpocket

## About The Pull Request

Adds a subtype of the security belt for department guards. They get to spawn with it, and it holds all their gear nicely.
The lockers are now just for extra ammo and clothing.

![image](https://github.com/NovaSector/NovaSector/assets/77534246/21bc5b50-7b2c-41cb-be1f-57a140dd8f7f)
![image](https://github.com/NovaSector/NovaSector/assets/77534246/aa4fbdff-5e99-49a1-b5c0-1df825bf0d7f)

## How This Contributes To The Nova Sector Roleplay Experience

Security belts for department guards was a suggested feature.
I agree with the suggestion, having a belt with all your job gear just makes sense. The gunset box, loose baton and flash/cuffs in the pocket slots was just clunky.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/NovaSector/NovaSector/assets/77534246/4eb8d0b3-7998-407d-8753-995a177b1500)

</details>

## Changelog

:cl:
image: Added departmental guard belts
qol: Department guards now start with their gear equipped in a spiffy looking belt
/:cl:

2024-04-11 20:10 UTC, honkpocket commented
![image](https://github.com/NovaSector/NovaSector/assets/77534246/f83f272a-4000-4b62-bf39-05dee1bb3655)

2024-05-02 16:28 UTC, GoldenAlpharex commented on modular_nova/modules/goofsec/code/department_guards.dm
>  /*
```suggestion

/*
```

2024-05-02 16:30 UTC, GoldenAlpharex requested changes
Sprites are cute, I like them! This PR is good to go once the requests have been addressed (doesn't have to be me that merges it).

2024-05-02 16:30 UTC, GoldenAlpharex commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/ammo_box/advanced/pepperballs(src)
While you're here, do you think you could modularize all of these properly? I think they were added in here by mistake, instead of being put in a modular file.

2024-05-02 16:30 UTC, GoldenAlpharex commented on modular_nova/modules/modular_weapons/code/pepperball_gun.dm
> -/obj/item/storage/toolbox/guncase/nova/pistol/pepperball
Why was this removed?

2024-05-03 21:01 UTC, GoldenAlpharex requested changes
Just a quick nitpick.

2024-05-03 21:45 UTC, merged