[SEMI-MODULAR] Taur rework Pt. 0: Lays groundwork for some taur reworks, gives taur legs names, etc.
NovaSector/NovaSector pull request #1954
Opened 2024-04-13 02:08 UTC by nikothedude

## About The Pull Request

THIS PR IS A ENTRY IN A SERIES OF PRS INTENDED TO GIVE TAURS FLAVOR

Main design doc: https://hackmd.io/@NikoTheGuyDUde/rJ7C9HPe0

### Changes
Taur bodies are now properly subtyped
* Allows taur-specific behavior

Taur legs now have custom names 
* Appear in examine and health analyzer

## How This Contributes To The Nova Sector Roleplay Experience

Read the main design doc. In short, taurs have very exotic anatomy that isnt explored much, and the game would be greatly diversified if we added some mechanical differences.

Having the legs show up with different names, again, helps exemplify their odd anatomy, and should hopefully cut down on medical going WE NEED TO FIX YOUR LEG when its actually your snake body.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
</details>

## Changelog

:cl:
code: Taur bodies are properly subtyped
add: Taurs now have custom leg names
/:cl:

2024-04-13 02:08 UTC, nikothedude commented
https://github.com/NovaSector/NovaSector/pull/1953

2024-04-13 13:26 UTC, nikothedude commented
worth mentioning, a lot of things like wounds still use limb.plain_text, meaning the taur leg renaming isnt perfect

2024-05-06 19:34 UTC, GoldenAlpharex requested changes

2024-05-06 19:34 UTC, GoldenAlpharex commented on code/__DEFINES/~nova_defines/limbs.dm
> +// This is a limb to be used on taurs.
```suggestion
/// This is a limb to be used on taurs.
```

2024-05-06 19:34 UTC, GoldenAlpharex commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +					if(limb.bodytype & BODYTYPE_ROBOTIC || limb.bodytype & BODYTYPE_TAUR) // NOVA EDIT ADDITION - Taur limbs show their full name
```suggestion
					if(limb.bodytype & BODYTYPE_ROBOTIC || limb.bodytype & BODYTYPE_TAUR) // NOVA EDIT ADDITION - Taur limbs show their full name - ORIGINAL: if(limb.bodytype & BODYTYPE_ROBOTIC)
```

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +	var/right_leg_name = "back legs"
Document these variables, please.

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +	organ_type = /obj/item/organ/external/taur_body/horselike
Make `/datum/sprite_accessory/taur` have `organ_type = /obj/item/organ/external/taur_body/horselike`, it's going to remove a lot of the duplication that can be seen here.

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +	organ_type = /obj/item/organ/external/taur_body/horselike
```suggestion
```

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +	organ_type = /obj/item/organ/external/taur_body/horselike
```suggestion
```

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +	organ_type = /obj/item/organ/external/taur_body/serpentine
```suggestion
```

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +	organ_type = /obj/item/organ/external/taur_body/serpentine
```suggestion
```

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +	organ_type = /obj/item/organ/external/taur_body/tentacle
```suggestion
```

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +/obj/item/organ/external/taur_body/horselike/synth
You don't seem to be defining the `/obj/item/organ/external/taur_body/horselike` type anywhere, you should have it somewhere, just to avoid any bad surprise.

2024-05-06 19:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +/obj/item/organ/external/taur_body/spider
Why not use "left legs" and "right legs" here, since spiders have legs on the sides of their body?

2024-05-06 19:55 UTC, nikothedude commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +/obj/item/organ/external/taur_body/horselike/synth
my bad

2024-05-06 19:59 UTC, nikothedude commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +/obj/item/organ/external/taur_body/spider
good point

2024-05-06 20:12 UTC, GoldenAlpharex approved these changes
This seems fine to me now.

2024-05-06 20:16 UTC, GoldenAlpharex commented
This should hopefully be fine to go without a test-merge, since it shouldn't theoretically actually change much.

2024-05-06 20:41 UTC, merged

2024-05-06 20:56 UTC, nikothedude commented
> Your Fix/Feature pull request is currently below zero (-14). Maintainers may close future Feature/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

quiet worm