[SEMI-MODULAR] Taur rework Pt. 2: Quadruped taurs (Part one)
NovaSector/NovaSector pull request #1976
Opened 2024-04-14 03:37 UTC by nikothedude

## About The Pull Request

**BASED ON https://github.com/NovaSector/NovaSector/pull/1954**

THIS PR IS A ENTRY IN A SERIES OF PRS INTENDED TO GIVE TAURS FLAVOR

Main design doc: https://hackmd.io/@NikoTheGuyDUde/rJ7C9HPe0
Quadruped design doc: https://hackmd.io/@NikoTheGuyDUde/rJzJiBPgC

### Changes
Quadruped taurs can now wear saddles
* Takes the back slot, but allows piggybackers to retain their hands when riding
* Enables the jousting component - Calvary time

Types of saddle
* Riding - 2 hands, no storage
* Saddlebags - 1 hands, backback level storage with one main caveat: Open accessability
* * Anyone who alt clicks the user can access their storage
* * Just take the gun out of their bag and kill them with it
* * Uses components, so can be added to any item

## How This Contributes To The Nova Sector Roleplay Experience

Read the main design doc. In short, taurs have very exotic anatomy that isnt explored much, and the game would be greatly diversified if we added some mechanical differences.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/NovaSector/NovaSector/assets/59709059/46c8d6b7-590a-4a98-9475-60591eb426b2

</details>

## Changelog

:cl:
add: Quadruped taurs can now wear saddles, which give the rider free hands to use during a piggyback and enables the jousting component
add: Saddlebags for quadruped taurs, which are one-handed saddles that allow anyone to access their storage by alt clicking the wearer
/:cl:

2024-04-14 03:38 UTC, nikothedude commented
more changes to quadruped taurs may come in the future, i just wanted to get this one out

2024-04-14 03:41 UTC, nikothedude commented
also, the icon sprites are placeholders until zydras gives me better ones

2024-04-14 17:27 UTC, nikothedude commented
> pulling from someone's bag probably should take a (small) action bar simply so people can't like driveby pick pocket or do it midfight while people are squirming around and stuff
> 
> or opening the bag instead, so people can't have a free instant search

that was kinda the idea, to just be able to take the gun out of the taur's storage and shoot them with it

im kinda at a crossroads - i wanna increase the storage of the saddlebags but i could also go this way and just keep it satchel adjacent with a access/insert/removal delay

i feel the first is a funnier idea since it leans even more heavily into the caravan animal aesthetic

2024-05-08 18:12 UTC, nikothedude commented
just discovered a issue will fix it before undrafting

2024-05-08 19:36 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/item.dm
> +	if (SEND_SIGNAL(src, COMSIG_ITEM_MOB_CAN_EQUIP, M, slot, disable_warning, bypass_equip_delay_self, ignore_equipped, indirect_action) & COMPONENT_ITEM_CANT_EQUIP)
i agree, this is a bit ugly and not the best use of signals, but i did a bit of sluething and i think this is the best way to do it without a upstream rework of the equip chain because its kinda ugly

2024-05-08 19:37 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/item.dm
> +	if (SEND_SIGNAL(src, COMSIG_ITEM_MOB_CAN_EQUIP, M, slot, disable_warning, bypass_equip_delay_self, ignore_equipped, indirect_action) & COMPONENT_ITEM_CANT_EQUIP)
MAYBE itd be a better idea to put a signal on item/equipped() instead, but this also prints a "you are unable to equip" this message and all-in-all is a better place to represent a items inability to be equipped

2024-05-08 19:39 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/saddle_component.dm
> +	RegisterSignal(parent, COMSIG_ITEM_POST_EQUIPPED, PROC_REF(parent_equipped))
sadly, this doesnt work if youre moving a item from your hands to your back. you cant just return COMPONENT_EQUIPPED_FAILED off COMSIG_ITEM_POST_EQUIPPED, it just. literally wont work. it goes into the slot anyway

2024-05-11 20:50 UTC, nikothedude commented on code/modules/mob/living/carbon/human/human.dm
> +	return buckle_mob(target, TRUE, TRUE, piggyback_flags) // NOVA EDIT -- Original: return buckle_mob(target, TRUE, TRUE, RIDER_NEEDS_ARMS)
oh, this is a much better way of doing it. i dunno why i never thought of this

2024-05-14 20:00 UTC, nikothedude commented
DO NOT MERGE RN IM TESTING THE UNIT TEST TO SEE WHY ITS FAILING

2024-05-15 18:32 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/saddle_component.dm
> +			return TRUE
see codebus

2024-05-15 18:34 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/human.dm
> +		return FALSE
correct, and ridee means the mob being ridden
saying "they" is less explicit because you can put someone onto a taur that isnt yourself, meaning it could be either the ridee or rider

2024-05-15 18:47 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/atom_storage.dm
> +	SEND_SIGNAL(parent, COMSIG_STORAGE_REMOVED_ITEM, thing, remove_to_loc, silent)
will do

2024-05-15 18:52 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/human.dm
> +		return FALSE
oh. that works yeah

2024-05-15 23:08 UTC, nikothedude commented on modular_nova/modules/customization/modules/taur_mechanics/code/item.dm
> +	if (SEND_SIGNAL(src, COMSIG_ITEM_MOB_CAN_EQUIP, M, slot, disable_warning, bypass_equip_delay_self, ignore_equipped, indirect_action) & COMPONENT_ITEM_CANT_EQUIP)
IIRC, returning COMPONENT_EQUIPPED_FAILED doesnt work here if youre equipping from your hands to a slot, which is what we're preventing

2024-05-25 06:59 UTC, FlufflesTheDog commented
I absolutely adore the saddle functionality
Though I'm wondering if the little bag animation that plays on the whole character is intentional- or if it just can't reasonably be disabled.
Also, dunno how it'd be made to not conflict with the strip menu, but being able to buckle others to yourself would be very convenient.

2024-05-25 16:27 UTC, nikothedude commented
> I absolutely adore the saddle functionality Though I'm wondering if the little bag animation that plays on the whole character is intentional- or if it just can't reasonably be disabled. Also, dunno how it'd be made to not conflict with the strip menu, but being able to buckle others to yourself would be very convenient.

the animation was speifically coded, is intentional, and is a. silly b. a way to determine if your inventory was externally opened

2024-05-31 12:04 UTC, honkpocket commented
![image](https://github.com/NovaSector/NovaSector/assets/77534246/ef8aa446-0f52-4640-97e4-afa5f894500c)

has got some layering/offset issues. my character's arms and hands are hidden + its position is a bit off in general.

2024-05-31 17:00 UTC, nikothedude commented
I HATE OFFSETS AAAAAH

2024-05-31 19:18 UTC, nikothedude commented
waiting on https://github.com/tgstation/tgstation/pull/83604 for the next fix

2024-06-04 22:19 UTC, nikothedude commented
delayed by the same fucking signal again: https://github.com/tgstation/tgstation/pull/83727

2024-06-08 19:43 UTC, nikothedude commented
all issues addressed

2024-06-08 22:31 UTC, FlufflesTheDog requested changes

2024-06-08 22:31 UTC, FlufflesTheDog commented on modular_nova/master_files/code/game/objects/items/stacks/sheets/sheet_types.dm
> +  new/datum/stack_recipe("saddlebags", /obj/item/storage/backpack/saddlebags, 5, category = CAT_CONTAINERS)
```suggestion
	new/datum/stack_recipe("saddlebags", /obj/item/storage/backpack/saddlebags, 5, category = CAT_CONTAINERS),
```
tabs vs spaces

2024-06-08 22:31 UTC, FlufflesTheDog commented on modular_nova/master_files/code/game/objects/items/stacks/sheets/sheet_types.dm
> +  new/datum/stack_recipe_list("saddles", list( \
```suggestion
	new/datum/stack_recipe_list("saddles", list( \
```
same

2024-06-08 22:31 UTC, FlufflesTheDog commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +	var/list/taur_specific_clothing_y_offsets
this isn't being treated like a lazylist elsewhere, and is runtiming. Properly either set up a list of all zeros as the default, or use LAZYACCESS

2024-06-08 22:31 UTC, FlufflesTheDog commented on modular_nova/modules/customization/modules/taur_mechanics/code/saddle_component.dm
> +	if (!isliving(equipper))
```suggestion
	if (!isliving(equipper) || (slot & (ITEM_SLOT_HANDS|ITEM_SLOT_POCKETS))
```
early return if it's only in our hands, also saves some signal overriding runtimes

2024-06-08 22:31 UTC, FlufflesTheDog commented on modular_nova/modules/customization/modules/taur_mechanics/code/saddle_component.dm
> +	if (!(slot & (ITEM_SLOT_HANDS|ITEM_SLOT_POCKETS)))
```suggestion
	if (slot & (ITEM_SLOT_HANDS|ITEM_SLOT_POCKETS))
```
non-taurs are currently able to equip these

2024-06-08 22:39 UTC, FlufflesTheDog commented
Also, canine taur sprite seems to be layered too low when facing north
canine vs deer, body and tail rendering under clothes
![image](https://github.com/NovaSector/NovaSector/assets/25628932/6699dc93-8ca9-4b28-91ec-3f00f6e75533)

And the sprite for the saddlebag item is really thin, which makes it a bit awkward to directly click

2024-06-17 21:18 UTC, nikothedude commented
theres a few outstanding issues with this pr (see the msot recent comment) and im basically done with nova, so instead of leaving it open forever im just gonna close it because i am not gonna work on this anymore

i encourage interested parties to take over and finish this in my stread

2024-06-17 21:18 UTC, closed without merging