Tweaks to the Interlink disposal access/room
NovaSector/NovaSector pull request #2079
Opened 2024-04-19 04:26 UTC by iliyaxox

## About The Pull Request

Fixes #2074 (the disposal room's conveyor belt not being linked to the conveyor switch) while also adjusting a few things in the Interlink disposal room along the way, and replacing a few of the trash bins with disposal units.

## How This Contributes To The Nova Sector Roleplay Experience

It gives the disposal room flavor. Instead of it being a dull and dark room, it now looks like an actual disposal room that has a purpose, even if illustratively so.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/NovaSector/NovaSector/assets/64568243/28f6219c-5e22-445e-947b-5bd9f02aa3c9)

and diffbot
</details>

## Changelog
:cl: Chelxox
fix: The Interlink disposal room's conveyor belt now works.
qol: The Interlink disposal room has been expanded a little bit.
qol: A few of the trash bins in the Interlink have been replaced for disposal units.
/:cl:

2024-04-19 16:22 UTC, Zergspower commented
You've a CI issue to fix,

Bring back the disposal that was just outside the shuttle as that's actually the most used one i've seen

ensure that the blastdoor cannot under any circumstance be destroyed/opened/manipulated

2024-04-19 17:25 UTC, SomeRandomOwl requested changes

2024-04-19 17:25 UTC, SomeRandomOwl commented on _maps/map_files/generic/CentCom_nova_z2.dmm
> +/area/centcom/interlink)
This should probably be a fake door, or some indestructible impassable turf below it, because at the moment someone can spend a lot of time smacking it and just break out of the map itself.

2024-04-19 17:27 UTC, SomeRandomOwl commented
Also, in game screenshots and not editor screenshots for proof of testing

2024-04-21 06:48 UTC, Zergspower commented
Nah,  you can edit and change em if power goes down or they open - it's how you reprogram the ID's for cargo shutters. As long as they're the ones that share the same space they'll work.

2024-04-23 00:15 UTC, merged