Makes Blueshift atmos less insufferable
NovaSector/NovaSector pull request #2164
Opened 2024-04-24 10:00 UTC by 1393F

## About The Pull Request
unspaces blueshift atmos, everyone I have talked to did not like half of atmos being in space

## How This Contributes To The Nova Sector Roleplay Experience
Makes playing atmos on Blueshift much nicer

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/NovaSector/NovaSector/assets/59183821/c7c31636-d77c-43dd-ae1d-55722ae17d70)
![image](https://github.com/NovaSector/NovaSector/assets/59183821/bd3e8e9e-3130-4c6a-b49f-ffa48ed2d11b)

</details>

## Changelog

:cl:
qol: Blueshift atmos in no longer spaced
/:cl:

2024-04-24 12:59 UTC, honkpocket commented
This is not the solution. Re-map it or wait for someone to re-map it, using the fill tool as a quick fix is super undesirable.

2024-04-24 17:08 UTC, Exo-212 commented
There's probably a more nuanced improvement to be made here. For example, you could leave most of the eastern side of the atmos area as space tiles, but build a pressurize the area where the pumps are located to make it easier for atmos techs to use the gas tanks.

As-is, each powered element of the pipes out there is on its own scuffed turf that's part of a disconnected room that starts in an airlock and only covers a few turns.

That room could be expanded, for instance.

2024-04-24 20:04 UTC, 1393F commented
> There's probably a more nuanced improvement to be made here. For example, you could leave most of the eastern side of the atmos area as space tiles, but build a pressurize the area where the pumps are located to make it easier for atmos techs to use the gas tanks.
> 
> As-is, each powered element of the pipes out there is on its own scuffed turf that's part of a disconnected room that starts in an airlock and only covers a few turns.
> 
> That room could be expanded, for instance.

thank you for your suggestion, I have decided to use your idea
![image](https://github.com/NovaSector/NovaSector/assets/59183821/53256946-4585-4541-8740-7819c4a8dfe9)
I hope this version will be more to everyone's liking

2024-04-24 20:12 UTC, honkpocket commented
> > This is not the solution. Re-map it or wait for someone to re-map it, using the fill tool as a quick fix is super undesirable.
> > ![image](https://private-user-images.githubusercontent.com/77534246/325228571-04a2d5ac-7ff2-4406-83f1-20f29333fd58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODU5NjEsIm5iZiI6MTcxMzk4NTY2MSwicGF0aCI6Ii83NzUzNDI0Ni8zMjUyMjg1NzEtMDRhMmQ1YWMtN2ZmMi00NDA2LTgzZjEtMjBmMjkzMzNmZDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE5MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YzllY2U1NDZhMmZmZmUwZDQ5MTdhMmRjYjg1N2FjYjMwYzY3ZjkyYmIwOTQyMWQ1MmNiNjYwMjMzMTFkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JAL8Kxm-8bNdsbdksR96i70xLvrFCvyPFGg0X81AbCE) like ???
> 
> if you are trying to give actual feedback or suggestions, state your actual concern, do not just paste an image and type "like ???" these types of comments are not helpful

Then read the rest of the comment?

2024-04-24 20:13 UTC, 1393F commented
> Then read the rest of the comment?

the entire thing is not helpful, look at Exo's comment on how to give useful feedback

2024-04-24 22:28 UTC, sqnztb commented
I am also of the mindset of this looks awful.

It's super lazy and putting the APC down in the airlock below the rest of the pumps doesn't really make any sense since it's completely separated from the rest of the 'upper' atmos.

![image](https://github.com/NovaSector/NovaSector/assets/28007787/ae04e592-8171-434f-9cf1-9258f4d56b59)
What. Come on now.

![image](https://github.com/NovaSector/NovaSector/assets/28007787/9828e360-8c23-4767-9908-b09a0ec9d6ce)
Pipes shouldn't be going through walls where avoidable.

I wouldn't be opposed to a remapping but just throwing some walls and floors down and calling it a day isn't the way to go about doing it. I would rather the whole inner `/area/space/nearstation` zone be flipped to `/area/station/engineering/atmos` than this, since that would power the whole area so you can still do funny pipe things.

2024-04-24 22:31 UTC, Jolly-66 requested changes
I don't like either solution proposed.

If the issue is that atmospherics is outside, then the entire sub department needs to be remapped. Doing these haphazard solutions is a nothing more than a band-aid solution, while also creating something aesthetically unpleasing.

2024-04-24 22:38 UTC, Exo-212 commented
> I don't like either solution proposed.
> 
> If the issue is that atmospherics is outside, then the entire sub department needs to be remapped. Doing these haphazard solutions is a nothing more than a band-aid solution, while also creating something aesthetically unpleasing.

For me, the problem that needs addressing is that only a few turfs out by the atmos tanks can support powered atmos piping.

Which makes adding/removing filters and pumps out there wildly inconvenient.

If smaller map changes like this are too blunt, 

> I wouldn't be opposed to a remapping but just throwing some walls and floors down and calling it a day isn't the way to go about doing it. I would rather the whole inner `/area/space/nearstation` zone be flipped to `/area/station/engineering/atmos` than this, since that would power the whole area so you can still do funny pipe things.

I think this ^ would be a good temporary solution that would be less disruptive.

2024-04-24 22:41 UTC, Jolly-66 commented
>good temporary solution

I do not want temporary solutions. I want permanent solutions.

2024-05-09 10:48 UTC, 1393F commented
too busy to work on

2024-05-09 10:48 UTC, closed without merging