Splish splash, adds mermaids and merdudes
NovaSector/NovaSector pull request #2458
Opened 2024-05-14 18:54 UTC by honkpocket

## About The Pull Request

This PR adds a mermaid-type taur, it deletes your legs! Intended to be used with supporting quirks like paraplegic or entombed. 

Its still a WIP:
- [ ] Make the modsuit sprites

## How This Contributes To The Nova Sector Roleplay Experience

Unique character aspects brings flavorful RP, also the sprites are pretty!

## Proof of Testing

![Kozw1EIfsB](https://github.com/NovaSector/NovaSector/assets/77534246/9d1df949-70fb-41b0-a47b-6cd1a9ac4112)

More soon.

## Changelog

:cl:
image: Adds mermaid taur types!
image: Adds modsuit icons for the new mermaid taur type!
balance: Modsuits can be worn even when missing limbs.
code: Tweaks taur flags to support the new mermaid type.
/:cl:

2024-05-14 19:37 UTC, nikothedude commented on code/__DEFINES/~nova_defines/inventory.dm
> +#define STYLE_TAUR_MERMAID (1<<5)
honestly reading this made me realize how we should probably change this into a "sprite priority list" as since taur bodies are OOP

not asking you to do this, but mermaids would be fine if like they took snake sprites if a mermaid sprite wasnt available

2024-05-14 19:50 UTC, nikothedude commented on code/modules/mod/mod_activation.dm
> +	///NOVA ADDITION - Enable MODsuits on characters with missing limbs
please either lock this only behind mermaids or justify the implications behind it

2024-05-14 23:09 UTC, Iamgoofball commented
okay but how do they stay upright when there's no water

2024-05-14 23:38 UTC, nikothedude commented
> okay but how do they stay upright when there's no water

they dont
no legs

2024-05-15 09:07 UTC, TetrakoHateThis commented
We need markings for different fishy scale types so we can have like various carps, angelfish or barbs!

2024-05-22 22:29 UTC, GoldenAlpharex requested changes
I'm still not entirely sure why this one needs to be legless, I feel like it's going to be mainly an inconvenience more than anything, if they have to crawl on the floor unless there's no gravity, and if they somehow can move around just fine normally, then I feel like this is a bit counter-intuitive, as they're losing access to a lot of things, and also can no longer take damage from their legs (which was one of the reasons why taurs kept invisible legs to begin with).

2024-05-22 22:29 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +///Prevent organic legs from being granted if prevent_leg_insertion is flagged TRUE
No need to add actual documentation here, if it already has documentation.

2024-05-22 22:29 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/surgery/organs/taur_body.dm
> +//(the above can_attach_limb proc edit still allows synthetic limbs to pass)
Ditto here.

2024-05-22 22:29 UTC, GoldenAlpharex commented on modular_nova/modules/taur_mechanics/code/mermaid_taur.dm
> +//proc called before a move happens to see if we are given control
```suggestion
/// proc called before a move happens to see if we are given control
```

2024-05-22 22:29 UTC, GoldenAlpharex commented on modular_nova/modules/taur_mechanics/code/mermaid_taur.dm
> +//Adds a signal allowing the use of their tail for navigation in pressurized zero g
The code doesn't check for there being an absence of gravity.

2024-05-22 22:29 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/taur_types.dm
> +	organ_type = /obj/item/organ/external/taur_body/mermaid/synth
Why do these need to be legless, exactly? I'm not sure to be following the logic here.

2024-05-22 22:29 UTC, GoldenAlpharex commented on modular_nova/master_files/code/modules/clothing/base_clothes.dm
> +	var/worn_icon_taur_mermaid
Document this please (and ideally the ones above and below too, but it isn't a hard requirement here.)

2024-05-22 22:29 UTC, GoldenAlpharex commented on code/modules/mod/mod_activation.dm
> +		if(module.active && module.allow_flags != MODULE_ALLOW_INACTIVE)
What's this here for?

2024-05-23 00:54 UTC, Nerev4r commented
> I'm still not entirely sure why this one needs to be legless, I feel like it's going to be mainly an inconvenience more than anything, if they have to crawl on the floor unless there's no gravity, and if they somehow can move around just fine normally, then I feel like this is a bit counter-intuitive, as they're losing access to a lot of things, and also can no longer take damage from their legs (which was one of the reasons why taurs kept invisible legs to begin with).

You can easily grab a gravity harness, or make use of the new entombed + paraplegic combo which is even easier and roundstart tbh; I wouldn't want to see mermaids sliding around on the floor.

2024-05-23 01:06 UTC, nikothedude commented
you can also just disable the legs

2024-05-23 01:07 UTC, nikothedude commented
actually yeah. why not just disable the legs, and disable the feet slot (maybe). the legs are still there, they just are only aquatic

2024-05-23 11:29 UTC, honkpocket commented
I'm steadfast on the no-legs mechanic. Don't bother arguing about it, having to play with the handicap is key to my concept.

Delayed until #2565 is merged.

2024-05-23 11:36 UTC, honkpocket commented on code/modules/mod/mod_activation.dm
> +		if(module.active && module.allow_flags != MODULE_ALLOW_INACTIVE)
The original coder who made this Nova edit forgot that some MOD modules are allowed to run on an inactive modsuit, so it would still shut them down 4nr.

2024-05-23 20:54 UTC, nikothedude commented
an additional bonus of disabling the legs instead of removing would be removing the ability for modsuit limbs to deploy on non existent limbs (which again should be moved to Only apply to mermaids and their lack of legs)

2024-05-24 13:10 UTC, honkpocket commented
Delayed until my SS13 hiatus is over.

2024-05-24 13:10 UTC, closed without merging