The Lore Committee Finally Appears: Species chargen blurb replacements
NovaSector/NovaSector pull request #2620
Opened 2024-05-23 02:44 UTC by Ephemeralis

## About The Pull Request

For the past six or eight months or whatever, the Lore Committee has been *cooking*.

Not everything is out yet, but many races have had updated settings and explanations of their basic lore put on [our wiki](https://wiki.novasector13.com/wiki/Nova_Sector_lore). For those that have, I've decided to take the leap in getting them properly in-game where people can see them.

I've also renamed Mothman to Mothperson to keep in line with literally everything else, and added a `wikilink` var to the species datum for use elsewhere later on.

This is just a draft PR for the moment. Wording and verbiage may change.

Note for lore contributors: if you want to add to this, DM or highlight yooriss on discord with **just your blurbs**. I'll handle the code formatting stuff for you, so don't fret if you look at any of this and go *what the fuck is that*.

TODO:
- [x] Humans
- [x] Ethereal
- [ ] Felinid
- [ ] Flyperson?
- [ ] Xenobiological Slime Hybrid
- [ ] Lizardperson
- [x] Mothperson
- [ ] Podperson
- [ ] Snailperson
- [ ] Vox Primalis
- [ ] Akula
- [ ] Dwarf
- [ ] Ghoul
- [ ] Humanoid (generic)
- [ ] Anthromorphic Insect
- [ ] Anthromorph
- [ ] Skrell?
- [ ] Tajaran (WIP, someone working on it)
- [ ] Vulpakinin (WIP, someone working on it)
- [ ] Xenomorph Hybrid
- [ ] Hemophage
- [ ] Synthetic Humanoid
- [ ] Teshari
- [ ] Primitive Demihuman
- [ ] Ashwalker
- [ ] Primal Podperson

## How This Contributes To The Nova Sector Roleplay Experience

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  TBD
</details>

## Changelog

:cl: The Lore Committee, yooriss
add: Humans now have a new, lore-accurate blurb in character creation.
add: Ethereals now have a new, lore-accurate blurb in character creation.
add: Mothpeople now have a new, lore-accurate blurb in character creation.
/:cl:

2024-05-23 03:34 UTC, SomeRandomOwl requested changes
To fix CI

2024-05-23 03:34 UTC, SomeRandomOwl commented on tgstation.dme
> +#include "modular_nova\modules\lore_species\code\ethereal.dm"
```suggestion
#include "modular_nova\modules\lore_species\code\_species.dm"
#include "modular_nova\modules\lore_species\code\human.dm"
#include "modular_nova\modules\lore_species\code\mothpeople.dm"
#include "modular_nova\modules\lore_species\code\ethereal.dm"
```

2024-05-23 09:47 UTC, Ephemeralis commented
I'll handle the CI stuff when they're all in otherwise I'll have to change the stupid thing every time (thanks vscode)

2024-05-23 14:23 UTC, Zergspower commented
Curious, are you grouping synths into one? They're only grouped and mixed for coding reasons (IPC/Synths)

2024-05-23 14:27 UTC, Ephemeralis commented
> Curious, are you grouping synths into one? They're only grouped and mixed for coding reasons (IPC/Synths)

Honestly, not sure. Think there's any chance we could reasonably compress them into one category?

2024-05-23 14:39 UTC, Zergspower commented
> > Curious, are you grouping synths into one? They're only grouped and mixed for coding reasons (IPC/Synths)
> 
> Honestly, not sure. Think there's any chance we could reasonably compress them into one category?

Give how vastly different the two are, e.g. TV heads with no mouth, i'm not sure. The generalized canon are there are 3 types of synths on station, IPC's, Synthetic 'Anthros' and Synthetic humans

2024-05-23 14:40 UTC, Ephemeralis commented
On second thought, species compression will probably fuck with people's preferences pretty hard, so... I guess we'll just spinoff some blurbs for the different synthetic types (and other similar cases)

2024-05-23 14:41 UTC, Zergspower commented
I imagine the generic anthro category is going to be stuck with the same issue

2024-05-24 01:10 UTC, Iamgoofball commented
the 50 billion furry and robot categories with no mechanical differences between eachother should 100% be condensed and the only reason I didn't condense them into a generic Furry and Robot race during tgui prefs is because epic Gandalf testmerging directly to live put me on a massive time crunch

2024-05-27 21:31 UTC, W4rd3nn commented on modular_nova/modules/lore_species/code/ordoht.dm
> +		"Historically a civilization of vast intellect and power, the modern Ordoht are little but a shadow of what they once were. A victim of their own technological prowess, the Ordoht fell prey to a se
```suggestion
		"Historically a civilization of vast intellect and power, the modern Ordoht are little but a shadow of what they once were. A victim of their own technological prowess, the Ordoht fell prey to a self-replicating terraforming technology they themselves developed, turning their homeworld Ordo (and everything) into something entirely and horrifyingly new.",
```
:3 this is great otherwise. Once the Three Kings is done, I'll either edit the blurb myself or if this PR is still open i'll suggest the changes :3

2024-05-27 21:32 UTC, W4rd3nn commented on modular_nova/modules/lore_species/code/ordoht.dm
> +		"Historically a civilization of vast intellect and power, the modern Ordoht are little but a shadow of what they once were. A victim of their own technological prowess, the Ordoht fell prey to a se
could also do with a general grammar pass tbh but that can come later

2024-05-28 07:04 UTC, wheat-mallow commented on modular_nova/modules/lore_species/code/ordoht.dm
> +		"Historically a civilization of vast intellect and power, the modern Ordoht are little but a shadow of what they once were. A victim of their own technological prowess, the Ordoht fell prey to a se
they all definitely need a grammar pass - practically all of the blurbs that are mine are just like 5-10 minute split screen summaries written directly into vscode

2024-06-27 15:59 UTC, Ephemeralis commented
Given the lack of interest from the LC in filling out the remainder of the blurbs, I've decided to just go ahead with what we've got here.

2024-06-27 16:10 UTC, Nerev4r commented on modular_nova/modules/lore_species/code/tajaran.dm
> +		similar to that of a terran cat, save for being bipedal. \
bipedal, and having mirrored duplicate organs such as carrying two tails, and often four eyes.

2024-06-27 16:30 UTC, Nerev4r commented
as for Teshari,

species description probably along the lines of like

Teshari are a species of diminutive, scavenging dromaeosaurs known for their hypersocial behavior and nomadic, traditional cultures. Organized into packs for a variety of purposes, anywhere from finding carrion to working factories, from traveling across the galaxy to artisanal and artistic technology and goods, Teshari are incredibly communal compared to other races, known for  intricate expressions of the self despite their collective nature, especially when it comes to gender. 

lore prob'ly like

Teshari, an umbrella term loosely translating to 'Wanderer,' are a collection of possibly thousands of species all sharing one common ancestor. Sharing many traits with Terran raptors of old, they have bodies that are extraordinarily well-feathered with scales to be found on 'bald' spots, with highly developed claws and teeth, four ears detecting the faintest sounds.

However, beyond their hypersocial and xenophilic nature, Teshari are equally known for their great ambition and scraping out every little chance for success for themselves and their packs. They are very driven, owing to their original nature as scavengers and opportunistic predators, accomplishing incredible tasks in their groups -- even seemingly-daunting construction tasks are easily handled within a manner of days. Teshari have many technological achievements without outsider assistance, due to their psychology working better with larger and larger groups, rather than the inverse found in humans. 

They are still a nomadic people that incorporate their traditional culture into their technology; rarely mass-producing things, and having a great focus on craftsfolk making artisinal goods with a high focus on aesthetics. Packs are willing to travel for long distances as long as their togetherness is maintained, picking up members at their leisure along the way, leading to their race reaching practically every corner of their home planet. Found hitching rides with the Grand Nomad Fleet, in deep space as surveyors, or practically all over the Orion Spur, their migratory natures have found them across the cosmos working on all sorts of projects together.

2024-06-27 16:41 UTC, Nerev4r commented
as for slimes,
description can be like

Slimes, referred to with a variety of languages word simply for 'slime', are amorphous fauna entirely native to bluespace. Liquid, like everything else in this celestial space, slimes are an opportunistic group of omnivores utilizing practically anything as a food source. Comprised of a fluid medium, the true seat of a slime's consciousness is their 'core,' a sort of nucleus hosting a substantial electrical charge at all times; if removed, it will cause immediate and irreparable disintegration of the surrounding body.

for lore probably like

Normally located on the other end of the Bluespace-Realspace barrier, slimes primarily prize plasma as a fuel source, masses of them on the other side creating dimensional friction to cause plasma wells to form. The Ordoht have historically been known to use the substance as bait to intentionally pull slime out from the other side, exploiting a common feature: mimicry. Slimes are capable of incredible feats of learning and overall mental agility, necessary to navigate the currents and eddies of their home dimension. Within even a few months of existing in realspace, a slime can be brought to resemble almost any organism it typically interacts with, and able to react to speech in under an hour. Further work can give one a roughly humanoid shape, upon which the Ordoht would recognize them as capable of complex learning-- the foundations of becoming a person.

Despite their amorphous and shape-shifting nature as liquids, slimes that reach the point of personhood can become rapidly affixed to a single identity. Thought of by the Ordoht as 'mimicking themselves' and looping in on their own habits, a slime's disposition can become extraordinarily individualistic and defined in most cultures it's exposed to. Even before and after the point of peak memetic saturation, slimes will ruthlessly chase any new cultural or philosophical information to either adopt or discard.

2024-06-27 17:09 UTC, Nerev4r commented
as for vulpkanin,
species description along the lines of like

Thought to be a genetic offshoot from another race, Vulpkanin are a species somewhere in the middle of hyenine and vulpine. Standing at impressive heights and carrying some genetically adapted traits of 'terror spiders,' Vulpkanin share doubled and mirrored organs; two hearts, often four eyes, and in some cases double mouths as well. The species demographics are split between 'Soulborn,' born naturally, and 'Vatborn' created by the Armada as custom genetic projects from the culture's greatest.

as for lore,
The Vulpkanin Armada, a semi-nomadic armed caravan, finds its' roots from the species prehistory, an unknown apocalypse causing their star to break down much faster than expected. Escaping the blastwaves of a supernova, Vulpkanin society started fresh off the televised killing of their last noble dynasty of Zealot-Kings. Rebuking the ideals of one spiritually, mentally, and physically perfect leader, this framework has broken down and become a responsibility unto everyone.

Vulpkanin society is dictated by their core philosophy, the Way of Two-Handed Perfection. The original definition of this doctrine is known to be the belief that a Vulpkanin has the potential to reach two forms of flawlessness: physically and mentally. In their eyes, a strong body with a weak mind is evil at worst and a careless beast at best while a strong mind with a weak body is simply seen as depressing; the Left-Handed path calling for a flawless body, and the Right-Handed path calling for a flawless soul. Their absolute obsession with self-improvement has given them the reputation for wanting to be 'stronger for the sake of strength,' and the need to prove that strength being thought of as the birthplace of several ideas still growing more prevalent in their society. 

Across the Armada, in every role from warrior to pilot to merchant to even cooks, a system of Rankings has been devised as a sort of culture-wide set of leaderboards. Any Vulpkanin whose Ranking numbers above 25% are considered the ‘mid-class' while the 'high-class' consists of the top 5%. Formally, only the top one thousand in any given category of the Ranking are able to submit their genetic information for the creation of a new Vatborn. It's thought that this system ensures Vulpkanin do their best to 'sharpen themselves' against each other, competing for not only the social status of a high number, but for the rights to have their genetic material contribute to an artificially-grown legacy. Automated sensors, commendation and condemnation submitted to the database by fellow Vulpkanin and large-scale shows of accomplishment or dishonor all have a place in deciding ranking.

2024-08-14 20:31 UTC, closed without merging

2024-08-14 20:46 UTC, Nerev4r commented
🗣️