Snowglobe Station - A new icemoon station for nova!
NovaSector/NovaSector pull request #3207
Opened 2024-06-22 23:50 UTC by MrSunabouzu

## About The Pull Request

A new station, a nova specific ice moon station called Snowglobe station! This is the first gamedev thing i've made in 4 years since shipping black mesa and it was a blast. I'd love to share it! The station 3 is z levels. z3 is the main station level. Almost all rooms and departments are on it, z2 is a sprawling basement full of rooms to loot or renovate, and amenities supporting rp interactions! The service hallway is modeled lightly after a shopping mall, and designed to be very friendly to navigate. To help facilitate traitors, ladders exist in every maint tunnel on z3 so a neer do-well can disappear into the labyrinth below.

This station implements no new assets or features as it is, but there is a non-functional room that I plan on adapting into a space elevator. I didn't know how to dev for byond until recently. The intent is to allow tarkon and other space areas to exist when the map is rolled, but I feel like that work is substantial enough i'd benefit from knowing if that spot is better used for say, a construction zone.

The planet side features are very generation heavy, I only use z3 for external infrastructure. The hope is that over time the addition of more ruins will make snowglobe a map that is fun to explore the mini-content others make. So I put aside as much space as possible for it!

I'm also quite proud of the name. Sphere shaped and on an ice moon, get it?

## How This Contributes To The Nova Sector Roleplay Experience

New maps are cool! And throughout my time playing a consistent wish i've seen from people in ooc is another snow map so they can roleplay their ice cats. I think a second snow planet station would let us justify making more things FOR that biome or supplementing anything that upstream makes for it. Also the dorms are meticulously designed so support roleplaying cuddling with someone next to a roaring fire while you watch a blizzard outside. I believe this to be peak.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![1](https://github.com/NovaSector/NovaSector/assets/34666436/0ad6e99e-a2a0-4064-b7c6-71608715e258)
![2](https://github.com/NovaSector/NovaSector/assets/34666436/5ae9b7d2-dabb-4ec1-a3fc-e0a8a14151f7)
![3](https://github.com/NovaSector/NovaSector/assets/34666436/38ca791a-9ad1-470e-b23e-cfda75715796)
![4](https://github.com/NovaSector/NovaSector/assets/34666436/4523e084-c7ce-421d-a623-31bf9307edcd)
![5](https://github.com/NovaSector/NovaSector/assets/34666436/a5c53222-d24c-41a3-bf31-77cfc5b0030f)
![6](https://github.com/NovaSector/NovaSector/assets/34666436/11658349-c04a-4949-a0d8-b521ee874d45)
</details>

## Changelog

:cl:
add: Snowglobe Station, a new icemoon station
add: unused fluff assets to be implemented in a later update for snowglobe
config: adds new areas to station_areas in modular_nova
config: adds snowglobe to maps.txt
config: adds snowglobe to automapper blacklist
/:cl:

2024-06-22 23:55 UTC, MrSunabouzu commented on config/maps.txt
> +	#default
oh. oops i forgot birdshot was default originally

2024-06-23 01:58 UTC, Jolly-66 commented on config/maps.txt
>  map deltastation
Make sure to revert/fix this.

2024-06-23 06:46 UTC, Iamgoofball commented
did a double-take at that username, not gonna lie

2024-06-23 18:44 UTC, Zenitheevee commented
Rid us of the dreaded Automapper.

Let the dawn of a fresh, Non-TG maps rise.

2024-06-24 21:19 UTC, Iamgoofball commented on _maps/nova/automapper/automapper_config.toml
> +[templates.snowglobe_icecats_lower]
You should not be using automapper templates on Nova original maps. Just map the content in yourself.

2024-06-25 07:33 UTC, MrSunabouzu commented on _maps/nova/automapper/automapper_config.toml
> +[templates.snowglobe_icecats_lower]
This is the solution agreed upon in the discord mapping thread, with the consultation of the server owner and zerg. It will not be hard baked.

2024-06-25 13:15 UTC, Zergspower commented on _maps/nova/automapper/automapper_config.toml
> +[templates.snowglobe_icecats_lower]
It's fine, it's a ruin that's also on icebox and i'm not maintaining 2 versions of the same thing

2024-06-25 15:47 UTC, Iamgoofball commented
As a reminder, come August, there is a very large visual redesign of the worldspace coming with the Wallening from the upstream, and I highly doubt you guys will be skipping it. Here's some WIP shots, not all assets have been moved to the new visuals yet(we've currently got a large bounty going for this at /tg/ to wrap it up in time) but come August 1st, we're shipping Wallening at /tg/ and it will come down here as a result, so you may wish to be ready to redesign your map to accommodate for this new visual style.

![image_-_2024-06-06T120353 429](https://github.com/NovaSector/NovaSector/assets/4081722/4537a2bc-e913-4e51-8ee5-d45bef4849b6)
![walleninglava](https://github.com/NovaSector/NovaSector/assets/4081722/c184dbc9-f723-44c0-9172-2ccdbb7da29a)

2024-06-25 16:01 UTC, Zergspower commented
yeah we're ... thrilled... yay...

2024-06-25 16:03 UTC, Iamgoofball commented
Yeah, it's gonna be a bit of an adjustment period and the maps are going to need a visuals pass, but we'll finally have a visual perspective that doesn't look like ass as a result.

2024-06-25 16:05 UTC, Zergspower commented
ngl Shiptest did it right a while back, but this isnt the place to bitch about the list of things i hate about this new look. We have however started to look at our own maps and cried at the task ahead though

2024-07-01 22:24 UTC, Zergspower commented
Been a while sorry about that - no energy at all with how busy work is

One tip i can give you is how to use the hide feature - in the environment tab the eyeball there if you click it will put checkboxes next to all the items.
![image](https://github.com/NovaSector/NovaSector/assets/22140677/144704dc-cd26-43f3-86f1-23b64c88b828)

Meaning you can hide entire groups such as objects, then select specifically which ones you want shown and it makes you smack your forehead often times on how easy it is to see it that way



<details>
<Summary>Disposals </Summary>
Shared Engineering Storage has a stray chute but no pipes
![image](https://github.com/NovaSector/NovaSector/assets/22140677/9678df9a-283f-441a-95e8-076ec0add514)

Engineering Security Post in a similar state
![image](https://github.com/NovaSector/NovaSector/assets/22140677/68502e5c-c4bd-4f59-b6f6-1c90f9a50802)

CE's Office is missing Disposal Pipes
![image](https://github.com/NovaSector/NovaSector/assets/22140677/232fcecd-4963-48ca-854e-a7e935fd01fd)

Actually looks like Engineering was missed on the disposals run, so i'll let you manage that before rechecking.
![image](https://github.com/NovaSector/NovaSector/assets/22140677/427c74d9-8716-4f02-9c07-a552d54db078)

Dorms Disposal chutes Orphaned
![image](https://github.com/NovaSector/NovaSector/assets/22140677/d63faa10-db07-47cd-9c4b-606f146c9f4c)

Botany - Try to avoid sending pipes through walls as often as possible as it makes repairing harder to do - but as shown you have an extra pipe and trunk underneath the one placed
![image](https://github.com/NovaSector/NovaSector/assets/22140677/dc29a0f8-2c5a-4d1d-8717-55d73d9e8098)

</details>

<details>
<Summary>Atmos - these are important as unconnected pipes will make angry CI noises - plus the needing to breathe part </Summary>
Botany is missing scrubbers

![image](https://github.com/NovaSector/NovaSector/assets/22140677/ce8d4335-3e8c-4af6-86dd-97cdda150bd9)

SM Room - having distro and waste running through the entire room is generally not a good idea as it makes repiping fairly difficult, and currently your waste is hooked into the SM's waste as well
![image](https://github.com/NovaSector/NovaSector/assets/22140677/c1a7592d-54c1-440c-b0b7-ece73bd2fd66)

Scrubber outside of Science will need some sort of pump to push it into waste 
![image](https://github.com/NovaSector/NovaSector/assets/22140677/d90d342e-55e5-456c-9a23-6bad18ee8e91)

Maints above atmos seem to have pipes leading places but then dont connect
![image](https://github.com/NovaSector/NovaSector/assets/22140677/1c9285f0-ac5f-43f3-9908-98ba49db824e)

![image](https://github.com/NovaSector/NovaSector/assets/22140677/01a65e86-49b7-4452-b04a-1f411823cec5)

![image](https://github.com/NovaSector/NovaSector/assets/22140677/a69f638a-bc55-467f-906b-8cb5e6a14765)

![image](https://github.com/NovaSector/NovaSector/assets/22140677/350c4bb9-2083-464a-9f30-5e5ad415a1f2)

![image](https://github.com/NovaSector/NovaSector/assets/22140677/56b767e6-a85c-4dd6-b9a0-764ad87a8460)

![image](https://github.com/NovaSector/NovaSector/assets/22140677/7508a618-c2ed-4b5c-ac1d-075af700bdfd)

Maints above Psych similar issue
![image](https://github.com/NovaSector/NovaSector/assets/22140677/8befafe7-b372-46f3-858c-3d89d47b0b06)
![image](https://github.com/NovaSector/NovaSector/assets/22140677/b550615d-dbc9-4b43-b450-307c89e96fc7)

Abandoned Wrestling Arena
![image](https://github.com/NovaSector/NovaSector/assets/22140677/c68b1828-0d5e-4283-adfb-4284883e48e8)

Abandoned Cafeteria
![image](https://github.com/NovaSector/NovaSector/assets/22140677/a0a6c3c4-9d18-4aea-b6df-24ea0eeb745d)
![image](https://github.com/NovaSector/NovaSector/assets/22140677/091aec47-a9e0-4ed0-b276-0558d111bdc5)

Maints above Holodeck
![image](https://github.com/NovaSector/NovaSector/assets/22140677/90ec198a-4cfc-4fe2-a0e1-1b3138e7652e)

Outside Holodeck 
![image](https://github.com/NovaSector/NovaSector/assets/22140677/1769fc9c-f142-475e-a4bf-a114b12a491b)


</details>

2024-07-01 22:28 UTC, Zergspower commented
Any specifics to why the raptor pen is so far away?

And can that launcher for Ord travel that distance?

2024-07-01 22:29 UTC, Zergspower commented
Son of a bitch hold on Github desktop lied to me

2024-07-01 22:30 UTC, MrSunabouzu commented
> Any specifics to why the raptor pen is so far away?
> 
> And can that launcher for Ord travel that distance?

Oh its far away just because I thought itd be a good reward for exploring the otherside of what i lovingly call the Ankle Destruction Cliff

And yeah i yote a banana up to the detonation chamber unless ttvs go less distance on a driver

2024-07-02 07:16 UTC, Thlumyn commented
Hi, I've got a few comments as well, just as a fellow mapper

<details>
<summary>Atmos</summary>
It kind of feels like the crystallizer is an afterthought here: Like, the HFR gets its own room and floor design and then the crystallizer is just there. Maybe add some floor decals around it or something to make it look more like something mapped in vs something added later by an atmos tech. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/d1f9dc4e-b4a9-444b-adb0-a9ab4a390b53)

It looks like your gas tanks are missing the tank control computers, and the gas sensors (though you have the input vents, so theres no computer to control them).

![image](https://github.com/NovaSector/NovaSector/assets/102194057/2790e6fe-d9ef-4f15-884c-6fc4253b0348)

What is going into the mix input? I like the general idea of having atmos being a bit more free form like this, but it still looks weird to just have an injector going into nothing but an r wall, maybe you should have a pipe into pipe layer there to match the yellow ones? 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/fb7bea7c-6f79-46e5-9e3f-abdcb5fbc807)

I've got some concerns about this distro output here. 
Firstly, having the distro/scrubbers pipes under that Air to Distro pump will probably be a little annoying, because that looks like it would be the idea place to add in a layer adapter -> valves/pump -> layer adapt set up that atmos techs add to optimize distro. Same concern with that layer adapter right under it; that would be disconnected if that section were removed to add that. Also, it seems to be missing a thermo in the distro output (which, especially on an ice station is pretty important, as some people use the thermo to slightly overheat distro to counteract temperature loss. Also, there is no pump going into the waste loop.

![image](https://github.com/NovaSector/NovaSector/assets/102194057/1822b78b-d321-454d-9525-9a5705843c6c)

About that waste loop: 

It's usually nice to have a shutoff before they get filtered into gasses. Like, when the gasses get really hot, I like to turn on that so that we aren't filter overheated N2 and O2 back into the gas tanks which can lead to a hotter distro than expected. 

For example, ice box has it here: 
![image](https://github.com/NovaSector/NovaSector/assets/102194057/b1a69b8a-7cb6-486f-a545-83051ceb25cf)

The way this waste disposal loop has a valve from a planetary turf going into these filters means that when left alone, if that valve is open, it will just keep grabbing and filtering cold air from outside, put the extra cold O2 and N2 into the storage tanks and then adding the rest - probably cold CO2 into the general waste loop.... looking into it I probably should change this on my map to something like a pressure valve as well, o o p s

![image](https://github.com/NovaSector/NovaSector/assets/102194057/eebee3c5-bb82-4a93-a4a3-6626eae46408)

Atmos maints doors are general maints access so anybody can enter atmos 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/65541d43-c300-411b-a69e-a04277297e26)

Even if you plan for this to be replaced and hooked into custom pipes every time, you should probably add a port or something there so it doesn't complain about one way connections. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/07975269-0e97-4545-a919-f08582e16bf0)

HFRs usually have heavy shutters around them, not regular shutters, they'd burn right through regular shutters (and tbh probably heavy ones as well, but...) 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/1c0b1d6c-c564-4cb5-90f8-2e6e23b8c80b)
</details>

<details>
<summary>Engi</summary>
Bottom engi guard door has regular engi access 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/f3d298bd-3a57-45df-8bf2-fe8006ac09cc)

Why is this multilayer hub here? 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/72ab7c21-abdd-4ab9-81b6-555edfe27c04)

With the emitters being on the SMES output it might be problematic, both when the engine is starting (as they wont be getting any power to that cable until its already running) and if somebody were to upgrade the SMES and max input, it'd take the extra power that the emitters would be using. Ik there's been some issues recently with the cell changes causing brownouts and this might have been to avoid that, but hopefully the megacell PR should fix that 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/6ea27cdb-145f-4a89-bb4e-86d84755b105)

I know Granite said to move the pipes away from the center of the engine, and I think this is definitely an improvement, but its still a bit off to have them running under the windows like that. If possible, might want to change? Since removing pipes under windows can be a pain, Im sure you know that as an engi main. 
Also those windows should probably have plating under them and not r floor. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/861035f1-41eb-4eca-a343-3d39a8b3a141)

Nice. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/f29e86df-47c2-4b9c-a557-a7c40b90bc20)

Might want to compare with other maps, the engi lobby doors and some other doors in engi usually have a combination of either engi or construction access and yours just have engi. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/fdab5ac1-1a70-4fea-9b8f-eb544da1ba6c)

More engi doors that are just general maints access. On nova assistants get maints access for all departments, so they'd be able to enter engi from maints. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/fe17dc55-435c-4506-a863-b7f4d52c7f77)

Missing access on tcomms doors. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/1ce84666-781f-4279-ab01-3c9a92ceed72)

Tcomms isn't cooled... interesting. I'm assuming that a conscious decision there to make working on tcomms easier; but it also makes it easier to antags to break into tcomms as well. I advise putting a holopad in tcomms since AIs often check in during comms outages to bug the engineers working on it (I don't think they can stand not talking for a few minutes) 

Also, that's a nice looking cooling loop you have, interesting design. 

</details>

I'm still looking through the other departments

2024-07-02 08:05 UTC, Thlumyn commented
<details>
<summary>Service</summary>
Botany missing firelocks. Also it is missing a grinder. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/87193173-a047-4858-a3df-a7d1cac1f9e7)

With all the trays right next to each other, it makes it hard to control cross pollination. You might want to add windows/windoors between them, or separate them a bit so that they are not all touching. Void and blueshift are good examples of windows between the trays. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/15175192-7244-409a-bdec-6497586cbcd0)

With the kitchen, it'd be nice if there was something like donk ponkets or a cake batter to hold people over for a bit as the chef preps. 

Maints access directly into the kitchen 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/49c00e1d-f18b-499b-8c09-bb31befa20b6)

Kitchen is missing lockdown shutters. 

You might want to add a windoor here so it at least has the illusion of being a librarian only desk. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/be23d37d-ece0-4698-bce4-ea4ce55819a3)

Chapel Storage has crematorium access (not chapel office?) and I dont see any crematorium (the item) 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/55fc4f32-6923-4118-aba9-bf0a5538cfdd)

This door here can probably be normal maints access and not chapel office 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/f7799f37-edd5-4bd3-b4f3-915ec9f2f9a3)

Why make this door theatre access if anybody can walk down the stairs to get there? 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/b1f289f8-191a-47ef-8421-cac5f20b0233)

</details>

<details> 
<summary>Cargo</summary>
Might want to switch this computer and bounty pad - those conveyors might just grab up whatever somebody is trying to set down for a bounty, and not the cubes. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/826f3afc-90e3-4fee-bdc0-38223f4349c6)

Where are the buttons to control these shutters?

![image](https://github.com/NovaSector/NovaSector/assets/102194057/63b04287-e9c3-4813-9193-d4e7dfaa70e8)

This door should probably be mining, if the others are mining. 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/4669e85a-cc61-456e-bd33-82b260e9e1ca)

They have a mech but no power port 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/6e363bd4-2f25-484e-af4c-b24fa934d162)

Kheiral cuffs are a nice touch, but... isn't all the mining on station z levels? So suit sensors would work anyway

![image](https://github.com/NovaSector/NovaSector/assets/102194057/4bc6f2ba-8f7c-4a06-8c98-6bbf3fbdbf90)

I think these outdoor paths are just adorable

![image](https://github.com/NovaSector/NovaSector/assets/102194057/1fd84778-0771-4607-b18f-66746849235b)


</details>

Aaaannnd that's all the energy I have tonight. I'll try to look at more departments and mapping stuff tomorrow, or thursday

2024-07-03 02:21 UTC, Thlumyn commented
<details>
<summary>Xenobio</summary>
Xenobio is missing some things: plasma, a grinder, a water tank + fire extinguishers (for rogue slimes), monkey cube boxes

Any reasons why the air alarms in there have the mixing chamber access helper? 

![image](https://github.com/NovaSector/NovaSector/assets/102194057/2dd161b6-403b-497d-a486-a4d5a80963e0)

Also, there's no door anything between that science hall and the xenobio room so anybody with general sci access can get in. 
</details>

2024-07-03 03:48 UTC, MrSunabouzu commented
> Xenobio
> Xenobio is missing some things: plasma, a grinder, a water tank + fire extinguishers (for rogue slimes), monkey cube boxes
> Any reasons why the air alarms in there have the mixing chamber access helper?
> 
> ![image](https://private-user-images.githubusercontent.com/102194057/345259177-2dd161b6-403b-497d-a486-a4d5a80963e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzM2NTQsIm5iZiI6MTcxOTk3MzM1NCwicGF0aCI6Ii8xMDIxOTQwNTcvMzQ1MjU5MTc3LTJkZDE2MWI2LTQwM2ItNDk3ZC1hNDg2LWE0ZDVhODA5NjNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QwMjIyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2YzMGJmZjA4MTU3YmFlNTg1MjU3NjViZTk3YmI3NjU2ZmJiNjRlNGNhYTNiYmY1NTI0MGVmMDNhNWIxNGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tWw1gNJ5v-5AuFoDnXD2QnLN9T0DLC1e7NbmqxuPbyE)
> 
> Also, there's no door anything between that science hall and the xenobio room so anybody with general sci access can get in.

Good catches, all of these posts! thank you so much for looking over snowglobe! Implemented all the suggested changes except the chapel crematorium access, because i put the crematorium in there o o p s

As for the lack of tcomms cooling, that could bite me in the ass if upstream decides temperature control matters. My solution honestly would be some passive vents that are exposed to the outside and heat radiator pipes on the inside. Cheap, cools it but kind of badly so it can be improved on, funny osha-violating design.

Lastly the air alarm in xeno, its like that since to my knowledge in code that means "if they are a scientist, let them use it" and that last 5x5 chamber is designed to be flooded with a specific gas of the scientists choosing, probably bz. The air alarm is how I intend them to inject the gas in there, just turning it on via alarm. ill admit its whimsical but theres a scrubber right there so how bad can they fuck it truly?

2024-07-05 23:28 UTC, Jolly-66 requested changes
Cursory review of some things I've noticed:

Go over every non-maint door and double check for firelocks. I found some doors without firelocks.

For departments such as Security. Engineering and Science, please double check your r-wall usage (or rather, security). Walls that face maintenance or the main hall NEED to be secured. Internal walls, walls that are used INSIDE the department, do not need to be secured. Rooms like the SM chamber, Ordnance, Head Offices and XB are exempt from this room for obvious reasons.

The same applies to windows. Reinforced windows need to be used on the outside. Usage of plasma glass should also be replaced with those windows (except in the SM chamber).

The clown and mime being spawned all over the station, on paper would be fine. But whenever we get this map ready for testing, clown/mime players are going to be disoriented from where they're starting (not to mention there is a clown spawn in maintenance!!). Keep them to the theater, backstage or even the bar/kitchen.

All dept sec checkpoints need to be devoid of sec stuff (records consoles). Department related consoles are fine however.

Double check window spawner tile turfs. There needs to be plating underneath them.

Double check the mapping verbs (active turfs, display intercom range) to make sure they're complicit.

2024-07-06 22:46 UTC, Jolly-66 requested changes
Some other quick nits before I inspect departments.

<details>
<summary> Nits </summary>

Please remove the light switches from the hallways. It realistically makes no sense. I know I told you to check the mapping tools, but you *really* don't need a light switch everywhere.

The plasglass/titanium tables need to be swapped out with any other table type. Regular reinforced/glass is fine, but no higher.

The chaos emerald lizards descriptions need to be changed. They feel memey and OOC. I'll accept them if their desc are based off of their names and aren't AS memey. A joke or two is perfectly fine.

There are also just, a TON of windows. Everywhere.

The bomb site is missing its camera (indestructible). I know its the bomb site, but spruce it up, it feels incomplete.
Also you really should put a *lot* of padding around this. A good max cap may destroy a nearby ruin and cause issues (if people are there)
![image](https://github.com/NovaSector/NovaSector/assets/70232195/f231745a-3ff7-429d-ad6b-4390905b5e45)

Swap the bathroom doors out with generic ones, and add door lock buttons inside the stalls.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/eaad0b2f-36eb-412f-ab94-f38590615795)

Tcomms AND tech storage need to be integrated better. They appear to be very shoe-horned in. Secure storage in tech storage can also be VERY easily broken in.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/eb26d1e2-9af2-470d-b1d5-97d181339a77)
![image](https://github.com/NovaSector/NovaSector/assets/70232195/47a82f30-a06f-41e3-b6fc-aab6e542d5b4)

I know they work, but it looks weird. Place the plastic flaps ontop of the chutes.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/b9fe5dfa-1a25-489f-947f-d76fbe43794f)

These are the same console code-wise.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/ad47b9f8-93be-477a-a25b-202607394cc0)

This entire section of maint needs to be redone and fleshed out more. Its essentially nothing but straight lines and bends.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/ea0bf67f-58c1-4fea-8657-cac605da1d25)

Remove SOME of the shipping containers in exchange for more crates and random nonsense.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/d2208de4-4df4-4b67-a52c-e165ee8701ae)

For these abandoned rooms, try to make them more derelict. Its strange having most of the machines intact.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/9296e590-9c97-4da3-86b3-8132b5bda7ad)

The beds here feel very out of place, please remove them.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/e139ed2d-e0c4-4673-964d-785e5d559cd7)

Coroner's office needs secure morgue trays.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/2d2be449-7884-4a1a-8d8d-b9433d8fcc22)

Rotate these bedsheets.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/4e6af34f-6143-42bb-8c7d-933760720119)

This pipe is not `visible`.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/9fa49573-ebe5-4f20-ae83-96667bf34898)

The burn/freeze chambers need their unique areas.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/cedef4d9-1bd7-4d8d-96f8-7e354545ae9e)

Make a subtype or use a different turf, these aren't actually cold turfs.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/2354118f-7fd0-4ee2-914d-6730ec05f07f)

Rejiggle the freezer. The freezer shouldn't be in maint like this, its only asking for trouble.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/c16a3e3c-e6ea-4d8d-8cce-ffdb768e04b5)

The chapel should have innate access to the burial grounds.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/ade80559-c6cc-4e1b-ac5e-e60be2d9ffc9)

We don't need two mining consoles.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/2494cc7a-ee99-47c8-88fe-b6062425a9c6)

Where is cytology?
![image](https://github.com/NovaSector/NovaSector/assets/70232195/0a17cd02-46a9-475d-9d77-c51f0dbb1bb9)

Clean up the siding here.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/f84fe27c-f398-456a-bea3-63e16680370d)

The 2x2 wall of hell. Readjust this.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/b104dc4a-5454-4b3d-9ef4-4d47e64cd67d)

Changing room could use a door lock, and move the curtains.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/a3602a8f-6ca9-4829-84f5-c7ce96b06f21)

Flavorful, but use regular candles. Feel free to throw in an extra box or two, as a treat.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/1751107e-1068-4b41-9248-5b1602c95cbc)

Please remove this cat bed in atmos, its very out of place.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/b7421c3a-95a3-4408-851c-9c4bfc14d8e5)

The atmos tanks need to be connected to the main pipe net roundstart.
![image](https://github.com/NovaSector/NovaSector/assets/70232195/3e35063e-dbef-4be8-a02d-bb8badb8e701)


</details>

2024-07-07 00:31 UTC, Iamgoofball commented
I do want to comment a bit more on this room in particular as it's very much an issue all of our downstreams have with mapping

![346301592-e139ed2d-e0c4-4673-964d-785e5d559cd7](https://github.com/NovaSector/NovaSector/assets/4081722/8895814f-3e74-4743-a6bb-856196b1669f)

This room has absolutely zero reason to exist in the in-universe conceit that this is a corporate workspace by a corporation for people doing the daily SS13 shift at. It only makes sense in the conceit of this being furry meet 'n fuck kingdom 13.

A lot of the downstream maps have this issue, and the only map I've seen pull it off convincingly is Blueshift because Blueshift is designed like a cruise ship and it's largely constrained to the heads of staff offices which are expected to be opulent, the promenade on the left side of z1 that's basically a bunch of empty businesses, and the permabrig, which the eternal joke about it being a retrofitted resort section for rich people turned into a prison due to its isolated nature makes immensely funny.

Try to remember, you're building a functional workspace that's, as of the shift starting, built to corporate spec to a T(except with corners cut where possible to save on money, because Nanotrasen is nothing but cheap); why would corporate spec include such a room?

2024-07-07 01:01 UTC, Iamgoofball commented
>Because its for an rp server. And sometimes people want to collaboratively write in an rp server in a room that's marginally harder to access so they are less likely to be disrupted by unwanted mechanical disruptions. Why would I design a station map for upstream and not the server I play on? Like I don't really care what the lore is on upstream. Its not for it.

Because it is an RP server, the station should make sense as a workspace especially because a high roleplay server like Nova Sector is expected to be realistic. It's out of place on a conceptual level because the kayfabe of the roleplay is that you're a bunch of people working on a space station, built by a corporation for people to work at. 

The Dormitories exist on an IC level because Nanotrasen understands their crew needs their privacy from time to time, allowing them to implicitly acknowledge "our crew fucks" without outright acknowledging that it's a common occurrence because this isn't Furry Meet N' Fuck Kingdom 13, this is Space Station 13.

The Dormitories also exist on an OOC and game design level because players be fuckin' and because players need a room they can bolt with plausible deniability to do bad guy things like assemble devices or buy traitor items off their uplink.

Nanotrasen very much exists in whatever exists as Nova's lore after the coup, and they very much still are the corner-cutting corporation that they are at /tg/ and at bay and at goon and at every single other server, because the core premise is still Space Station 13, it's why everyone's here and not at many of the other venues for collaborative roleplaying and writing. People wanna play SS13 because they wanna be immersed in SS13 while writing roleplay. It doesn't make sense in any stretch of the imagination for Nanotrasen to build public sex rooms for sex directly off of public hallways in their stations, or to haphazardly jam a bunch of beds into random rec-rooms for people to have sex on that are visible from the hallway

The issue that I have with this room is that it is not trying to be even remotely sneaky about this being the sex room for people to have sex. It could be louder about it, sure, but it's also not being quiet about it. It's not a side room that's out of the way and thus hard to find, it's hooked up to what appears to be a service hallway based on the green flooring with glass double-doors. If it were not for the presence of the pillow pile and the double-double beds, this would be a perfectly serviceable rec room and nobody would bat an eye. However, it's got a set of double-beds visible by someone walking by the doorway that don't really seem to have any purpose in the room.

Basically, it's the difference between a player going "oh, that's a neat place to have sex in that I just found" and "oh, that's the sex room, its for sex". One's cool and neat and makes the player feel like they found something cool. One's just checking a box on the list of things players expect to find on Furry Meet N' Fuck Kingdom 13.

2024-07-07 01:15 UTC, Iamgoofball commented
Minor nitpick I noticed while loading the map up in the editor to draft a revised version of that room to elaborate on my concerns and to provide constructive criticism:
![StrongDMM_fKN9Cua1LD](https://github.com/NovaSector/NovaSector/assets/4081722/18ec4550-3bcb-4de2-a8a4-f8c1295dcaf0)

The Gulag is not set up properly; it's not using the unique gulag area or generation-turfs so megafauna, mining fauna, and ruins can spawn in the gulag's area. Additionally, people can just mine straight down if they get lucky with RNG and reach the stairs up on the Z-level to get back to the station with ease. Please check out how Ice Box does the gulag with the turfs and areas and the plasma river moat, as escaping the gulag is supposed to be a challenge that requires game knowledge of how to deal with the plasma/lava and shouldn't involve running into megafauna right outside the front door.

I did want to give props to this though: the little chair sitting at the ore processing center is hilarious and is a great example of the good worldbuilding and attention to detail I'm used to seeing in your past mapping projects in other games.

![StrongDMM_9pZzGB0FCY](https://github.com/NovaSector/NovaSector/assets/4081722/18d8e6ac-93ce-496c-8a57-b865dedfe6ea)

2024-07-07 01:27 UTC, MrSunabouzu commented
> > Because its for an rp server. And sometimes people want to collaboratively write in an rp server in a room that's marginally harder to access so they are less likely to be disrupted by unwanted mechanical disruptions. Why would I design a station map for upstream and not the server I play on? Like I don't really care what the lore is on upstream. Its not for it.
> 
> Because it is an RP server, the station should make sense as a workspace especially because a high roleplay server like Nova Sector is expected to be realistic. It's out of place on a conceptual level because the kayfabe of the roleplay is that you're a bunch of people working on a space station, built by a corporation for people to work at.
> 
> The Dormitories exist on an IC level(and the goofy ass sex vendor that really could use a visual redesign pass to be more low-key) because Nanotrasen understands their crew needs their privacy from time to time, allowing them to implicitly acknowledge "our crew fucks" without outright acknowledging that it's a common occurrence because this isn't Furry Meet N' Fuck Kingdom 13, this is Space Station 13.
> 
> The Dormitories also exist on an OOC and game design level because players be fuckin' and because players need a room they can bolt with plausible deniability to do bad guy things like assemble devices or buy traitor items off their uplink.
> 
> Nanotrasen very much exists in whatever exists as Nova's lore after the coup, and they very much still are the corner-cutting corporation that they are at /tg/ and at bay and at goon and at every single other server, because the core premise is still Space Station 13, it's why everyone's here and not at many of the other venues for collaborative roleplaying and writing. People wanna play SS13 because they wanna be immersed in SS13 while writing roleplay. It doesn't make sense in any stretch of the imagination for Nanotrasen to build public sex rooms for sex directly off of public hallways in their stations, or to haphazardly jam a bunch of beds into random rec-rooms for people to have sex on that are visible from the hallway.
> 
> The issue that I have with this room is that it is not trying to be even remotely sneaky about this being the sex room for people to have sex. It could be louder about it, sure, but it's also not being quiet about it. It's not a side room that's out of the way and thus hard to find, it's hooked up to what appears to be a service hallway based on the green flooring with glass double-doors. If it were not for the presence of the pillow pile and the double-double beds, this would be a perfectly serviceable rec room and nobody would bat an eye. However, it's got a set of double-beds visible by someone walking by the doorway that don't really seem to have any purpose in the room.
> 
> Basically, it's the difference between a player going "oh, that's a neat place to have sex in that I just found" and "oh, that's the sex room, its for sex". One's cool and neat and makes the player feel like they found something cool. One's just checking a box on the list of things players expect to find on Furry Meet N' Fuck Kingdom 13.
> 
> There is a lot of very neat and very cool things about this map; I think overall it's a massive improvement on the planetary station design compared to Ice Box, which was our first attempt at a planetside map on /tg/ and has remained for ages mostly untouched outside of the few changes over the years. I just think it needs a little more polish to really fit in with the map lineup and the kayfabe of SS13 as a roleplay setting where people have sex occasionally.

wait do you really think i expect that to be the big erp room? the door doesn't even bolt, no one would want to do it there. its for like, if you legitimately want to continue an ic conversation. like this happens a lot to me on my time in rp servers, you find out your character and someone else's share similar ideals and the vibes are fun and you get to know each other via rp. like. platonically. "oh hey your character has the same views as mine on silicon rights? cool lets find a spot to talk" the quiet room or the library are the intended spots for such an activity to pan out. The beds are if your like. a caregiver irl and expect to be afk for 20 or so minutes but don't want to or cannot retreat to a dorm to idle. you go here, the place you park your funny sprite in the spaceman game. Hell even on goon there's a couple useless spaces on nadir and donut 2 that are just "yeah go here to talk privately". It didn't even occur to me until you pointed it out that this could be a focal point for public sex and like. yeah. it can. depends on the round and the server and the phase of the moon. Nova swings wildly between horny and not horny. 

That said, the nightclub is absolutely designed for what you just described. That's why it has an empty room where someone can put down in big bold letters "dont open horny inside". There's really no reason to erp in here when the nightclub is right there unless your like, willfully negligent of 18+ rules. The fact that is accommodates traitors and gives antags a blind spot to openly plot and shit is a side effect but pretty funny.

The next part i will say with my entire chest: the pillows are so my original character can cuddle atop their giant dragon girlfriend and just not do anything for about 2 hours while they enjoy small talk with her else instead of do their job. It's cute as fuck to roleplay mundane domestic bullshit. I am a villain in this way and do not repent.

2024-07-07 01:30 UTC, MrSunabouzu commented
> Minor nitpick I noticed while loading the map up in the editor to draft a revised version of that room to elaborate on my concerns and to provide constructive criticism: ![StrongDMM_fKN9Cua1LD](https://private-user-images.githubusercontent.com/4081722/346305875-18ec4550-3bcb-4de2-a8a4-f8c1295dcaf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTUzNDcsIm5iZiI6MTcyMDMxNTA0NywicGF0aCI6Ii80MDgxNzIyLzM0NjMwNTg3NS0xOGVjNDU1MC0zYmNiLTRkZTItYThhNC1mOGMxMjk1ZGNhZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDExNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAzZjQ5ODg4OTVkNmEzNGE3MGNjZGRmODQxMTBiYzgzNmQ3OGM0Y2MxYjVkYzE0NGIzMzdjOTA5NzRhOWM5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zRWt_aoT1VW0VWvVzgZ_MNs8rlaZjogh_SgoVo3T4KE)
> 
> The Gulag is not set up properly; it's not using the unique gulag area or generation-turfs so megafauna, mining fauna, and ruins can spawn in the gulag's area. Additionally, people can just mine straight down if they get lucky with RNG and reach the stairs up on the Z-level to get back to the station with ease. Please check out how Ice Box does the gulag with the turfs and areas and the plasma river moat, as escaping the gulag is supposed to be a challenge that requires game knowledge of how to deal with the plasma/lava and shouldn't involve running into megafauna right outside the front door.
> 
> I did want to give props to this though: the little chair sitting at the ore processing center is hilarious and is a great example of the good worldbuilding and attention to detail I'm used to seeing in your past mapping projects in other games. The camera directly above the beds with the privacy curtains is also a nice touch.
> 
> ![StrongDMM_9pZzGB0FCY](https://private-user-images.githubusercontent.com/4081722/346305965-18d8e6ac-93ce-496c-8a57-b865dedfe6ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTUzNDcsIm5iZiI6MTcyMDMxNTA0NywicGF0aCI6Ii80MDgxNzIyLzM0NjMwNTk2NS0xOGQ4ZTZhYy05M2NlLTQ5NmMtOGE1Ny1iODY1ZGVkZmU2ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDdUMDExNzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZlYjcyZGZmYjkzYWFhZjk2YTVlZDRjOTI1YWJiM2E4N2ZhZThjOGI2OTljMjgwNjlkZmYyM2YxY2UzODk2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qaLpGdJ0c4s5uIlJ23iceu3AWaVKAlyVvqHIKQsTeSk)

oh shit nice thanks this is just straight up useful. SDMM is a really intuitive tool but this is still my first map in is so I fucked up a lot of small specifics. I've never seen anyone use the gulag on an rp server so who knows how long this wouldve been busted.

2024-07-07 01:59 UTC, Iamgoofball commented
I hate to say this but a regular issue at Skyrat before the coup to Nova was people turning the whole ass Bar into a strip club and doing extremely public sex., so admittedly I've got some bias and PTSD from players being absolute dumbshits in relation to this, but yeah, fair, my bad for making assumptions about the reasoning for the beds, that makes more sense but at the same time makes me wish we had like, a recliner chair or a pool-side lounge chair style thing you could put there instead, as it'd communicate that way, way better than the full ass double-beds with sheets imho

>The next part i will say with my entire chest: the pillows are so my original character can cuddle atop their giant dragon girlfriend and just not do anything for about 2 hours while they enjoy small talk with her else instead of do their job. It's cute as fuck to roleplay mundane domestic bullshit. I am a villain in this way and do not repent.

amen, respect the hustle, this is god's work

2024-07-07 02:16 UTC, MrSunabouzu commented
> I hate to say this but a regular issue at Skyrat before the coup to Nova was people turning the whole ass Bar into a strip club and doing extremely public sex., so admittedly I've got some bias and PTSD from players being absolute dumbshits in relation to this, but yeah, fair, my bad for making assumptions about the reasoning for the beds, that makes more sense but at the same time makes me wish we had like, a recliner chair or a pool-side lounge chair style thing you could put there instead, as it'd communicate that way, way better than the full ass double-beds with sheets imho
> 
> > The next part i will say with my entire chest: the pillows are so my original character can cuddle atop their giant dragon girlfriend and just not do anything for about 2 hours while they enjoy small talk with her else instead of do their job. It's cute as fuck to roleplay mundane domestic bullshit. I am a villain in this way and do not repent.
> 
> amen, respect the hustle, this is god's work

Naw its cool dude its a touchy subject, nova's ruleset is structured in a way so that consent of the audience is considered. You do it in rooms with boltable doors or in a space that is clearly designed for private matters and can be marked in some way as "don't go in". A lot of people use the labeler or whatever to put "do not enter" on doors then weld it. Blueshift has something like this with its backroom but I don't think it went far enough, hence a changing room plus 2 3x3 booths to outright accommodate sex work in a way that isn't embarrassing. I've ended up very ride or die for erp in general because I believe it to be an excellent tool for gender exploration in general and I think the space deserves a modicum of dignity. It can be a really healing creative writing exercise under the right circumstances. My earnest hope is a lot of very small private communities steal my map to explore themselves in a natural and safe way. 

Oh yeah relatedly apparently jazztronauts ended up fueling a few furry circles in vr chat creatively so i'm basically realizing im a lgbt johnny appleseed and i think it rules.

2024-07-11 00:37 UTC, GoldenAlpharex requested changes

2024-07-11 00:37 UTC, GoldenAlpharex commented on _maps/map_files/Snowglobe/snowglobe.dmm
Here's a few preliminary things I noticed, it's not all of my feedback, but doing stuff in this format is pretty slow so I figured I'd send this now, at least.

<details>
<summary>Courtroom</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/acf3ed0f-059e-4f16-b228-3250902d5095)

I believe we usually have some intercoms on each side of the courtroom, so that the court case can be played over the radio.

</details>

<details>
<summary>Surgery rooms</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/f0bba3d0-6482-4823-aaf4-79eac1a9879f)

Usually, we make it so they can have a way to make their windows opaque, to grant patients privacy during operations.

Furthermore, I'd probably move the smartfridge down one tile, and then turn the directional windows into full-tile windows, otherwise I feel like it looks a little awkward with the door being right next to it.

</details>

<details>
<summary>Labor Shuttle Hallway</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/d4ab3eed-2d40-4483-9709-612dddafbba3)

It's surprisingly low in decals, it makes it look very plain and boring. I'd spruce it up a bit with some stuff around the edges, like most of the other rooms, at least. Same goes for the Corrections Officer Lounge that's just a little North from this screenshot's top, and in general, Perma and even Security as a whole need some sprucing up too, it's very monochrome and bland in there, as opposed to many other parts of the station.

</details>

<details>
<summary>EVA Storage</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/327738a6-a02e-44c0-afe8-1e2104fe44b2)

There's a weird wall on the outside, also there's a general lack of decals inside the room too.
</details>

<details>
<summary>Arrivals Shuttle computer in Bridge</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/2e6e7bb4-68e9-4291-a06d-1dbbf6ee1e2f)

I'm not really sure why there's an arrivals shuttle computer on the bridge, there's not really any use for it being there, you can't even see the arrivals shuttle from the bridge.

</details>

<details>
<summary>Bridge</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/475445d3-4a90-457a-ae61-8dba6a7da22c)

I'd move the entire bridge here one tile to the right, so it actually aligns with the hallway that leads to it. It messes with my OCD that it's off-centered, and it doesn't look like it has too much of a reason to be off-centered.

</details>

<details>
<summary>Law Office Benches</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/8f5cfa12-db97-4f03-bcf3-12b41774cb99)

They probably shouldn't be shifted up, it looks a little awkward because it clips into the wall and doesn't actually pixel-shift people up when they sit on them, so it looks like they're not really sitting on the bench.

</details>

<details>
<summary>Vents/Scrubber Placements</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/21314907-49b0-441e-8354-590d7977ed52)

As you can see in the upper example, a lot of vent and scrubbers seem to be placed around randomly, which make the rooms look a little messy, I'd recommend trying to make things look a bit more intentional (trying to go for symmetry, putting them generally in the middle of rooms/hallways, makes more sense visually and actually usually makes them work better).

</details>

<details>
<summary>Orderly's Office</summary>

![image](https://github.com/NovaSector/NovaSector/assets/58045821/06bf6e20-f3ca-4e22-9533-79eb13bad81f)

I'd probably add more windows around the airlock, otherwise you basically don't see anything in there.

</details>

2024-07-12 20:04 UTC, spockye requested changes
Nice station, good work!

Couple of errors i noticed while looking it over

<details>
<summary>errors</summary>
<br>

![image](https://github.com/user-attachments/assets/bda42e9c-e004-4bba-b0a6-d24f7c803a8d)
missing supply pipe (z2)

![image](https://github.com/user-attachments/assets/fb65ef15-7ed2-46ad-bb5a-442dc4462038)

Missing supply pipe (Z2)


![image](https://github.com/user-attachments/assets/0fcf36f5-c2d2-4934-b930-75d301063b6d)
supply unconnected from the grid (Z2)

![image](https://github.com/user-attachments/assets/ed8e627d-ea1b-491e-a42e-dc558ca4fbfa)

this isnt connected to anything. unsure if thats intentional


![image](https://github.com/user-attachments/assets/028d4ca5-810e-4f2b-bb81-159b1151b649)

seems like this was supposed to be connected? (z3)
</details>

2024-07-16 23:36 UTC, sqnztb commented
Played a bit over the weekend. Botany issues:
- The right windoors inside botany's tray quads require cargo access to open and shut. 
- The windoors leading down into the service hall require `service` access which means anyone from service can just come in the back. They should have `hydroponics`.
- Same for the kitchen.
- And the bar. 
- Additionally I'd like the desk windoors flipped from the south edge to the north, that way botanists can put stuff on the table and people can actually take the items off said table without you needing to leave the windoors open (giving access to botany to any table jumper).

Botany-specific issues aside: The request console in botany is an `east` one that is manually pixel shifted back to x0 and y-33. The CE's request console is the same. And the HOS's. And several others. Please don't pixel shift directionals like this. The whole reason the directionals exist is so you don't have to. Please audit all of these.

2024-07-17 00:16 UTC, MrSunabouzu commented
> Played a bit over the weekend. Botany issues:
> 
> * The right windoors inside botany's tray quads require cargo access to open and shut.
> * The windoors leading down into the service hall require `service` access which means anyone from service can just come in the back. They should have `hydroponics`.
> * Same for the kitchen.
> * And the bar.
> * Additionally I'd like the desk windoors flipped from the south edge to the north, that way botanists can put stuff on the table and people can actually take the items off said table without you needing to leave the windoors open (giving access to botany to any table jumper).
> 
> Botany-specific issues aside: The request console in botany is an `east` one that is manually pixel shifted back to x0 and y-33. The CE's request console is the same. And the HOS's. And several others. Please don't pixel shift directionals like this. The whole reason the directionals exist is so you don't have to. Please audit all of these.
> 
> Edit: and the dead body placers in the morgue. You only need ONE. Each placer adds 3 bodies to morgue trays and with 3 placers, you now have 9 bodies shoved into 6 trays. Remove the extras.

You are objectively right about the service tweaks so i've just done them and am about to upload it. Thanks! A few other departments would benefit from having two sets of windoors so I did that too.

Good catch on the request consoles, i copied them from other maps and just deleted and replaced each with an auto-name of the correct direction. Also removed two morgue markers.

2024-08-06 19:15 UTC, GoldenAlpharex approved these changes
It's been test-merged long enough, let's go and merge it!

2024-08-06 19:16 UTC, merged