Changes Redsec items and MODsuits to Bluesec
NovaSector/NovaSector pull request #3550
Opened 2024-07-05 14:47 UTC by Acantharctia

## About The Pull Request

This changes some items left from TG's Red Security to Nova's Blue Security theme.

List of items changed:

- Security Webbing;
- Security radios, Law and order radio, security radio encryption key;
- Safeguard and Security MOD suits;
- Pepper Shoulders, Criminal Capture, Mirage Grenade, Security Visor MOD modules.

## How This Contributes To The Nova Sector Roleplay Experience

Mostly to stop the color classing that happens with red and blue security items and also swipe any old red sec remnants.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/NovaSector/NovaSector/assets/96220088/1de720ef-772a-451a-be74-810dfc04dfe9)

![image](https://github.com/NovaSector/NovaSector/assets/96220088/e59b16b6-a800-4557-b026-d84da090a047)

![image](https://github.com/NovaSector/NovaSector/assets/96220088/f37ef065-0917-4ca6-b154-bc8b89465cf9) 

![image](https://github.com/NovaSector/NovaSector/assets/96220088/d4c526fb-c1b0-4cf2-984a-00db772ada1b)

![image](https://github.com/NovaSector/NovaSector/assets/96220088/770214e1-51d3-4a87-b4d1-4bdcba43c791)
_(Ignore the white pixel, it's fixed)_

  
</details>

## Changelog

:cl:
image: Changes security MODs to be blue along with other minor security items.
/:cl:

2024-07-05 23:27 UTC, Iamgoofball commented
Does it still need to be bluesec?

2024-07-06 09:49 UTC, zeroisthebiggay commented
i made a pr with bluesec modsuits featuring a brighter blue a while ago

2024-07-06 13:39 UTC, Acantharctia commented
> Does it still need to be bluesec? This shade of blue is kinda lame, makes it hard to see. Way too edgelord. Brighten that blue up a bit.

I'll probably so that, I keep thinking if it is too hard to see.

2024-07-06 22:54 UTC, GoldenAlpharex commented on code/game/objects/items/devices/radio/encryptionkey.dm
> +	greyscale_colors = "#2C5185#1E2447"
Does this change the actual color of the radio channel itself?
I don't assume that it does, but I just wanted to double-check just to be sure, as I think keeping the channel itself red helps better differentiate it from other colors in the chat. Blue would be too likely to mix in with the blue of the command frequency on light mode, for instance.

2024-07-06 22:58 UTC, GoldenAlpharex requested changes
I've not actually taken the time to review all of the individual sprites yet, though, but I wanted to at least quickly tell you about the location of the icons themselves, moving them out of the /tg/ master files.

2024-07-06 22:58 UTC, GoldenAlpharex commented on icons/mob/clothing/belt.dmi
So, if you want to recolor the icons, it should be done in a modular fashion, rather than changing the `dmi` files in the `/icons` folder. We ask for all icon changes to be made within the `/modular_nova` folder, as that doesn't create merge conflicts when someone upstream decides to resprite these for themselves.

If you need some help to then link those sprites to the items, feel free to ask in #development-code, it's really quite simple and we already do happen to have a lot of overrides for that in the code (I just don't remember the exact file location).

This goes for all the icon files in this PR.

2024-07-07 03:01 UTC, Acantharctia commented on code/game/objects/items/devices/radio/encryptionkey.dm
> +	greyscale_colors = "#2C5185#1E2447"
So basically  the encryption key sprite is like greyscale clothing, in that instead of set colors, it just does an approximation based on a hex value. Each encryption key has different values, and these two values are just what security's encryption key color will be.

Also, command is blue on light mode? Nice.

2024-07-07 03:03 UTC, Acantharctia commented on icons/mob/clothing/belt.dmi
Ah shit, I forgot about that.
Well, I'll probably have to revert some stuff after doing a small back up of what I currently have saved, but I figure porting those should be relatively easy.

If I need help, I'll reach out to someone in there.

2024-07-10 15:23 UTC, closed without merging