(Host Request) Replace Security department with Sol Federation Marine Corps
NovaSector/NovaSector pull request #3613
Opened 2024-07-07 22:16 UTC by Draganfrukts

99% of contributors who say "I'm never contributing again" never contribute again for real this time
## About The Pull Request

Adds a set of markings meant to go with a tail, a combination marking for belly slim & body tonage, and a new canine snout.

## How This Contributes To The Nova Sector Roleplay Experience

Frankly, it doesn't contribute to roleplay at all. But you can have cool sprites.

## Proof of Testing

![image](https://github.com/NovaSector/NovaSector/assets/51841793/eb1674f0-7c93-405d-b7ba-f1e7f2383d9f)
![image](https://github.com/NovaSector/NovaSector/assets/51841793/2fc07162-e644-4d20-b40b-fd5746625a0c)
![image](https://github.com/NovaSector/NovaSector/assets/51841793/720b7a30-75e2-4a58-a4e4-e3c8d1bf45f5)
![image](https://github.com/NovaSector/NovaSector/assets/51841793/553525ba-ec2a-41f2-8dfc-43ff1165a173)

You might notice a small visual bug on the side sprites. I've already fixed that after testing that it all works correctly.

## Changelog

:cl: Dragonfruits
image: Added Black-backed Jackal tail & matching markings
image: Added Canine (Alt) snout
image: Added "Belly Slim (Alt) + Body Tonage" marking
/:cl:

2024-07-07 22:18 UTC, Draganfrukts commented
The joke didn't even work because the PR thing in-game didn't show up & frankly I've never taken an L like this before

2024-07-07 22:34 UTC, Draganfrukts commented
Hey so I may be stupid and I might have added a redundant tails.dmi file in my sleep deprivation fueled PR process

2024-07-11 20:21 UTC, GoldenAlpharex requested changes
Outside of the tail not having a wagging animation, the sprites look mostly fine with me? The shading could use a tiny bit of improvement, but it's not *that* bad either, especially not when compared to all the other things we do have.

2024-07-11 20:21 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm
> +	gendered = FALSE
This was only mentioned in the changelog, I probably would've mentioned it in the rest of the PR body, just because it didn't seem to fit directly in with the rest of what's being added.

2024-07-11 20:21 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm
> +	name = "Jackal back fur accents"
```suggestion
/datum/body_marking/other/jackal_fur
	name = "Jackal Back Fur"
	icon_state = "jackalfur"
	affected_bodyparts = CHEST | ARM_RIGHT | ARM_LEFT
	gendered = FALSE

/datum/body_marking/other/jackal_back
	name = "Jackal Back Fur Accents"
```

2024-07-11 20:21 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm
> +/datum/body_marking/other/bellyslimtoned
```suggestion
/datum/body_marking/other/belly_slim_toned
```

2024-07-11 20:21 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/snout.dm
> +/datum/sprite_accessory/snouts/mammal/caninealt
```suggestion
/datum/sprite_accessory/snouts/mammal/canine_alt
```

2024-07-11 20:21 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
> +	name = "Black-backed Jackal"
```suggestion
/datum/sprite_accessory/tails/mammal/wagging/black_jackal
	name = "Black-Backed Jackal"
```

2024-07-11 20:21 UTC, GoldenAlpharex commented on modular_nova/master_files/icons/mob/sprite_accessory/tails.dmi
You made an undocumented modification to the monkey tail's wagging sprite, and I'm not entirely sure what said modification was either. You're going to want to remove that change, whatever it was.

2024-07-11 20:21 UTC, GoldenAlpharex commented on modular_nova/master_files/icons/mob/sprite_accessory/tails.dmi
Also, is it normal that your wagging tail sprite isn't animated?

2024-07-12 00:02 UTC, Draganfrukts commented on modular_nova/master_files/icons/mob/sprite_accessory/tails.dmi
Not sure what happened to the monkey tail, I'll check that out.

Also yes, last I checked having no wagging sprite means that if you do end up doing the *wag emote the tail will just disappear, unless we have a new variable to prevent that

2024-07-12 00:07 UTC, Draganfrukts commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/tails.dm
> +	name = "Black-backed Jackal"
"Black-backed" interpreted as one word

2024-07-12 00:08 UTC, Draganfrukts commented on modular_nova/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm
> +	gendered = FALSE
![image](https://github.com/user-attachments/assets/31848b7e-4c3c-4517-90c1-87be22889394)

2024-07-12 00:20 UTC, Draganfrukts commented on modular_nova/master_files/icons/mob/sprite_accessory/tails.dmi
I checked the monkey tail, compared it to the tails.dmi file from master, found absolutely zero differences. I'm going to cut and paste it in the new file just to be extra sure but I'm confident it's just IDB freaking out.

2024-07-12 01:29 UTC, Draganfrukts commented
![image](https://github.com/user-attachments/assets/30f7d107-f735-4010-9e4f-cdc8f21cc0da)
Not sure what's up w/dis

2024-07-13 23:24 UTC, Draganfrukts commented
No new requests for two days, marking conversations as solved.

2024-07-20 05:40 UTC, Draganfrukts commented
Made the black backed jackal tail non-wag. Every suggestion has been applied.
This should be ready to be merged @GoldenAlpharex

2024-07-23 19:48 UTC, GoldenAlpharex approved these changes
Looks good to me now!

2024-07-23 19:48 UTC, merged