Uh oh! The NT board of workplace safety is trying to blacklist the Akhter Co. Prybar!
NovaSector/NovaSector pull request #3635
Opened 2024-07-09 00:57 UTC by carpotoxin

## About The Pull Request

The frontier crowbar is no longer available to be imported directly.

## How This Contributes To The Nova Sector Roleplay Experience

Tries to dampen some agency from players who don't particularly need it.

## Proof of Testing

![UcsbFiIbKk](https://github.com/NovaSector/NovaSector/assets/77534246/d9e6a60d-28c3-450a-bb06-86cb2d55ba88)

## Changelog

:cl:
balance: removes the prybar frontier tool's availability from direct cargo imports
balance: the colony fabricator flatpack is 25% more expensive (1500cr)
/:cl:

2024-07-09 01:04 UTC, Nerev4r commented
comfortable with making it an import, not comfortable with removing both

2024-07-09 05:22 UTC, OrionTheFox commented
I *personally* feel a better solution would be making the Prybar and the lathe it comes from **properly** Engineering-restricted. Currently, Cargo can purchase the entire Fabricator round-start, as it's a "Restricted Import" - Imports don't have departmental restrictions implemented at all though. The only 'restriction' is not being available on the Public console.

The reason Jaws of Life (an objectively better, 2-in-1 tool) are less common is that they only have a single source, being the Engineering Protolathe. The only way to get one is to convince engineering you need one, or to get into the department to print one; even then, it also requires research, so that it's not a round-start tool. This PR, while a good start, ultimately just buries the problem, instead of actually addressing the issue of all-access advanced engineering gear.

2024-07-10 18:45 UTC, annikaRU commented
If the prybar is removed as a printable item, a crowbar substitute should be readded in its place

2024-07-10 23:43 UTC, Iamgoofball commented
a substitute already exists, it's called printing a crowbar

2024-07-11 10:18 UTC, annikaRU commented
> a substitute already exists, it's called printing a crowbar

This was meant for the RCF, as it only printed prybars

2024-07-11 16:16 UTC, desminus commented
Ideally we want to encourage break ins and petty crimes and the like among people as conflict and this seems analogous to it

2024-07-11 17:00 UTC, theselfish commented
There are multiple ways to break into a department. Most of them have a window near by, a windoor, etc etc.


The backpack fitting free to basically everyone budget Jaws makes it too easy.

2024-07-11 17:50 UTC, Iamgoofball commented
perhaps people can learn to break into areas via the powers of the long sealed away "mechanical toolbox" instead of letting people print an item that makes the access card system irrelevant

2024-07-11 18:39 UTC, GoldenAlpharex requested changes
I think it's fine to add it to the black market, but I don't think it should be removed from everywhere else. Part of the purpose of this tool is to make easier for people to do crime, so that your character doesn't necessarily need to know how to hack stuff to be able to break into places. It's a worse version of Jaws of Life, and they're already considered contraband, so I don't think it makes it any worse than having people print two small-sized items (a screwdriver and a multitool) to break in faster than with this tool.

2024-07-11 18:43 UTC, Iamgoofball commented
Characters who don't want to know how to hack can use the rest of the tools in the mechanical toolbox to break down windows and walls, or can social engineer into places. The prybar doesn't need to exist. You know this. I know this. Why are we pretending this tool needs to exist?

2024-07-12 00:25 UTC, OrionTheFox commented
> Ideally we want to encourage break ins and petty crimes and the like among people as conflict and this seems analogous to it

The prybar does not encourage conflict, it enables powergaming. 
Security willingly ignores any IC issues regarding prybars because they are too readily available and there is no real access restriction to obtaining them.
As I mentioned earlier, with Jaws of Life, the only way to get them is to physically have or illegally obtain access to the Engineering Protolathe, so it serves a triple purpose of
- Restricting how many appear on station
- Solidifying its place as engineering-only
- Giving Security even more content to pursue resulting conflict (not just 'they broke in using it' but also 'how did they obtain it in the first place?')

The Prybar does not actually achieve conflict because the outcome is always the offender just printing another one. It just wastes time and encourages lazy roleplay, slaps on the wrist, and zero story. Characters openly boasting about their contraband in front of security, who do not have the energy to bother with it again, and again, and again.

2024-07-14 02:01 UTC, RatFromTheJungle commented
> headmins raised a concern i hadnt thought of, here is a tweak to correspond. it can be printed again, but not imported directly. plus the machine that prints it is a little more pricier.

don't forget there's a crate that comes with it, 'colony starter crate' or something to that accord, which I believe isn't access locked (thought it should be)

2024-07-14 04:00 UTC, annikaRU commented
I believe that was intentionally left unlocked for people creating colonies, I am unsure however

2024-07-25 20:08 UTC, GoldenAlpharex requested changes

2024-07-25 20:08 UTC, GoldenAlpharex commented on modular_nova/master_files/code/modules/cargo/markets/market_items/tool.dm
> +	desc = "The infamous colonial crowbar, despite recent blacklisting by the Nanotrasen board of safety, still readily available on the black market. "
The description might just need to be adjusted to reflect the fact that it's still available from the fabricator, so it's not FULLY blacklisted.

2024-08-08 21:30 UTC, merged