Update SMES Performance [NO GBP]
NovaSector/NovaSector pull request #3839
Opened 2024-07-17 20:54 UTC by lessthnthree

## About The Pull Request

Upstream has finally smoothed out most of the issues related to power generation/storage since the power refactor. Particularly https://github.com/tgstation/tgstation/pull/84983 

This removes the overrides made to the raw SMES values. Given 84983 makes powering the station using solars actually viable, I'm leaving the SOLAR_GEN_RATE at 3500 instead of reverting to 1500. SMES will start with inbuilt tier 1, so real world tier 2 power capacities.

Includes adjustments to 84983 applicable to our APC overrides.

## How This Contributes To The Nova Sector Roleplay Experience

Intelligent APC charging and emitter priority means that the station doesn't need insanely buffed SMES to handle variations in station power. The intelligent charging also means solar panels will actually assist in contributing to baseline power generation.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/user-attachments/assets/a1d0de95-eb7b-4162-928b-16336c955510)

![image](https://github.com/user-attachments/assets/351a6be3-b348-41a4-bd94-53bee14d1f6b)

All APCs receive enough charging to maintain functionality. No more half the station at 100% and half at 0%.

![image](https://github.com/user-attachments/assets/b95d7cb7-1a93-4d13-b1e6-2ec268912f58)

Engine maintains power priority

</details>

## Changelog

:cl: LT3
del: Removed overrides for SMES rate and capacity
balance: SMES include a built in tier of throughput and capacity
/:cl:

2024-07-17 23:36 UTC, Zergspower commented on code/modules/power/smes.dm
> -	var/power_coefficient = 0
All this does is add 200KW off base and that's it, the idea of the override was to give each tier an upgrade boost.

2024-07-18 00:17 UTC, lessthnthree commented on code/modules/power/smes.dm
> -	var/power_coefficient = 0
As discussed, will leave power_coefficient at 0, but reduce input/output per tier to 300kW.

2024-07-18 00:43 UTC, GoldenAlpharex commented on code/modules/power/apc/apc_main.dm
> +			need_charge_for_channel = (cell.maxcharge * (APC_CHANNEL_EQUIP_TRESHOLD + 3) * 0.01) - cell.charge // NOVA EDIT CHANGE - Original: (cell.maxcharge * (APC_CHANNEL_LIGHT_TRESHOLD + 5) * 0.01) - cell
What do these changes do?

2024-07-18 00:59 UTC, lessthnthree commented on code/modules/power/apc/apc_main.dm
> +			need_charge_for_channel = (cell.maxcharge * (APC_CHANNEL_EQUIP_TRESHOLD + 3) * 0.01) - cell.charge // NOVA EDIT CHANGE - Original: (cell.maxcharge * (APC_CHANNEL_LIGHT_TRESHOLD + 5) * 0.01) - cell
Rounds the APC charge values to 10 and 20 percent. It's not a technical requirement, but aesthetics. Could also be accomplished by changing APC_CHANNEL_LIGHT_TRESHOLD and APC_CHANNEL_EQUIP_TRESHOLD.

The values were reduced to squeeze some more from the APC before things started to shut down.

2024-07-18 01:29 UTC, GoldenAlpharex commented on code/modules/power/apc/apc_main.dm
> +			need_charge_for_channel = (cell.maxcharge * (APC_CHANNEL_EQUIP_TRESHOLD + 3) * 0.01) - cell.charge // NOVA EDIT CHANGE - Original: (cell.maxcharge * (APC_CHANNEL_LIGHT_TRESHOLD + 5) * 0.01) - cell
I see.

2024-07-25 20:47 UTC, GoldenAlpharex requested changes

2024-07-25 20:47 UTC, GoldenAlpharex commented on code/modules/power/smes.dm
> +				power_coefficient = 8
This is an issue because it only takes one capacitor into account, now, instead of all of them (which I assume was an oversight)

2024-07-25 21:02 UTC, lessthnthree commented on code/modules/power/smes.dm
> +				power_coefficient = 8
No, an SMES only has one capacitor.

2024-07-25 21:53 UTC, GoldenAlpharex commented on code/modules/power/smes.dm
> +				power_coefficient = 8
That checks out, though it's still good practice to use `+=` here instead of just `=`, to take into account possible cases where they'd somehow have more than that, be it from a subtype or from an override or a balance change in the future.

You could also make all of this into `power_coefficient += 2 ** (capacitor.tier - 1)`, I just tested it and the behavior would be the exact same as what you have here.

2024-07-25 22:28 UTC, lessthnthree commented on code/modules/power/smes.dm
> +				power_coefficient = 8
Thanks, power_coefficient += 2 ** (capacitor.tier - 1) is nice. I wasn't sure how to write it in a way DM likes.

2024-07-27 21:19 UTC, GoldenAlpharex approved these changes
Should be good to go now!

2024-07-27 21:19 UTC, merged