Adds donor items for Thedragmeme and Snailomi
NovaSector/NovaSector pull request #3887
Opened 2024-07-19 23:28 UTC by Draggeru

## About The Pull Request

What the tin says, uses four slots for both people.

#3753 needs to be merged first

![peearrr](https://github.com/user-attachments/assets/b92174f3-0faa-4441-b8b7-400505febcc1)

There is a band-aid code fix in this PR to ensure that the scarf hoods work properly, the issue in reference is #85028 on the TG upstream

## How This Contributes To The Nova Sector Roleplay Experience

Rewarding contributors is very good!

## Proof of Testing

![peearrr](https://github.com/user-attachments/assets/a4d55ef6-02fc-455e-a94f-fb4b104db7dc)

Items work good

## Changelog

:cl: Thedragmeme
add: donator sets for Thedragmeme and Snailomi
/:cl:

2024-07-20 04:47 UTC, Draggeru commented
I have no idea why run linters are mad

2024-07-20 18:39 UTC, Draggeru commented on modular_nova/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	righthand_file = 'modular_nova/master_files/icons/donator/mob/inhands/donator_right.dmi'
Aw dangit

2024-07-22 21:51 UTC, GoldenAlpharex requested changes
Other than that, the sprites and the code check out!

2024-07-22 21:51 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +	desc = ""
You forgot a description on these.

2024-07-22 21:51 UTC, GoldenAlpharex commented on modular_nova/master_files/icons/donator/mob/clothing/thedragmeme.dmi
I'd rather we don't start naming icon files after people, it doesn't have to be separated from all the others, and if it somehow REALLY does, then it should be like, by item instead.

2024-07-22 21:51 UTC, GoldenAlpharex commented on modular_nova/master_files/icons/donator/obj/clothing/thedragmeme.dmi
I'd rather we don't start naming icon files after people, it doesn't have to be separated from all the others, and if it somehow REALLY does, then it should be like, by item instead.

2024-07-23 20:06 UTC, GoldenAlpharex requested changes
I might not have explained myself properly.

I think the sprites should be split into the existing donator files, so that they're coherent with the rest of the structure we have going on (which is to say, sprites are traditionally split between the slot they go in, like you can see in the following screenshot):

![image](https://github.com/user-attachments/assets/0591f03c-5a9a-45e4-9dae-aa19df89ae6f)

My apologies once again for the confusion.

2024-07-23 21:30 UTC, Draggeru commented
That turns everything into a huge pain in the ass since I now have to redo all of the sprite locations auuugh

2024-07-25 20:47 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/clothing/~donator/donator_clothing.dm
> +//Bandaid fix because obscurity is broken D:
```suggestion

//Bandaid fix because obscurity is broken D:
```

2024-07-25 20:48 UTC, GoldenAlpharex approved these changes
Should be good to go now once CI passes (sorry had to make that quick change first).

2024-07-25 21:14 UTC, merged