Adds a map lint to ban Nova dono plushies in maps
NovaSector/NovaSector pull request #3911
Opened 2024-07-21 17:58 UTC by Jolly-66

This is something that's set in stone, but not strictly enforced code wise. 

If I have to add a CL later I will. Do now worry later is my motto (burning in a horrific fire is another one of my mottos).

2024-07-21 18:30 UTC, SomeRandomOwl requested changes

2024-07-21 18:30 UTC, SomeRandomOwl commented on modular_nova/modules/loadouts/loadout_items/donator/personal/donator_personal.dm
> +	item_path = /obj/item/toy/plush/nova/dono/voodoo
```suggestion
	item_path = /obj/item/toy/plush/nova/donator/voodoo
```
Shoulden't this and all the others in this file be `donator` and not dono, because this will break every loadout entry

2024-07-25 20:53 UTC, GoldenAlpharex requested changes

2024-07-25 20:53 UTC, GoldenAlpharex commented on modular_nova/modules/customization/game/objects/items/dono_plushies.dm
> +		)
Ideally I don't do all of these because it's much faster for you to do it than for me to put every suggestion in. Trailing commas on multi-line lists, and the closing parenthesis should have one fewer level of indentation than the content of the list it's closing.

```suggestion
	attack_verb_continuous = list(
		"cuddles",
		"squishes",
		"blushes",
	)
	attack_verb_simple = list(
		"cuddle",
		"squish",
		"blush",
	)
```

2024-07-25 20:53 UTC, GoldenAlpharex commented on modular_nova/modules/customization/game/objects/items/dono_plushies.dm
I'd rename this one to `donator_plushies.dm`, instead of `dono_plushies.dm` (very minor nitpick, I know).

2024-07-25 20:53 UTC, GoldenAlpharex commented on modular_nova/modules/customization/game/objects/items/dono_plushies.dm
> +* As long as its not a balatant OOC refernce it can probably get used
```suggestion
* Plushies in this file are not usable in maps, so if you WISH for your plushie to /maybe/ be used in maps
* don't put in this file.
* Contact Golden if you want it to be usable on maps.
```

2024-07-27 00:40 UTC, Jolly-66 commented
m nbopt done

2024-07-27 21:19 UTC, GoldenAlpharex approved these changes
Should be good to go!

2024-07-27 21:19 UTC, merged