Adds a standard variant to the antenna-less bug snout.
NovaSector/NovaSector pull request #3948
Opened 2024-07-23 05:23 UTC by rutek-code

## About The Pull Request
I wanted to use a different antenna sprite than the one provided by the bug snout, but the antenna-less variant is locked to being over the hair. So I added another variant that can go below hair. I also renamed the original antenna-less variant to be more clear as to what it actually is.

## How This Contributes To The Nova Sector Roleplay Experience
This seemed like a simple oversight that needed to be fixed. It allows for (marginally) more character customization options in the game, which in turn (marginally) increases the possible character variety.

## Proof of Testing

![bugantennae](https://github.com/user-attachments/assets/ea20e101-3287-4844-ac8b-f716e61feb78)
The leftmost bug snout displayed is the one with antennae.
The center bug snout displayed is the one without antennae. Notice how it is **below** the hair layer.
The rightmost bug snout is the original antennae-less variant. Notice how it is **above** the hair layer.

## Changelog

:cl:
add: Adds a below-hair variant to the antenna-less bug snout.
/:cl:

2024-07-23 05:38 UTC, rutek-code commented
The Ouroboros integration test failure is completely unrelated- this PR doesn't have any changes involving mapping.

2024-07-24 07:06 UTC, rutek-code commented
Apologies, I am not quite used to the GitHub workflow yet.

2024-07-25 21:00 UTC, GoldenAlpharex requested changes
Other than this, the sprites seem fine to me.

2024-07-25 21:00 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/snout.dm
> +	name = "Bug (Top, No Antennae)"
Don't rename an existing sprite accessory like this, as they're saved in the savefiles by name, not by typepath, so doing this would require a migration script to ensure people don't suddenly get the new one you just added.

2024-07-26 00:06 UTC, rutek-code commented on modular_nova/modules/customization/modules/mob/dead/new_player/sprite_accessories/snout.dm
> +	name = "Bug (Top, No Antennae)"
this will necessitate awkward naming of the new snout type, but can be implemented.

2024-07-27 20:54 UTC, GoldenAlpharex approved these changes

2024-07-27 20:54 UTC, merged