Tgsigh
NovaSector/NovaSector pull request #4404
Opened 2024-09-15 14:46 UTC by Hardly3D

## About The Pull Request

Replaces *sigh, *cough, *sneeze with TG's while removing *esigh due to it being nearly a duplicate of TG's
Moth and Insect scream are merged since they return about the same audio
Additionally changes Human Scream 1's male screams to TG's and adding an unused female scream to it.
Vox and xeno emotes are left untouched.

## How This Contributes To The Nova Sector Roleplay Experience

With the recent TG emote sound PRs, I believe they currently sound and express the character better than what Nova currently has, you may check how they sound like by checking proof of testing.
Nova's male human screams were removed since the Male ones are ripped from Half-Life and is also pretty immersion breaking.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  

https://github.com/user-attachments/assets/7afc41af-dc9f-4f69-bf38-e8123d17361b

https://github.com/user-attachments/assets/794ae34e-dbdd-44df-b06b-0aaa780bf885

https://github.com/user-attachments/assets/c47ac88b-4ecb-49cd-a500-01db6deff5e7

Ignore the toolbox bit I got bored and forgot to stop recording there

https://github.com/user-attachments/assets/48d3ea57-1cb0-4018-9a61-03fc510e75f5

Vox sounds still work, I don't like them but this is out of scope

https://github.com/user-attachments/assets/2841f445-f610-48d7-8993-c616740d42df

</details>

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: Changed *sigh, *sneeze and *cough to TG's
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-09-26 02:18 UTC, Hemlock32 commented
I'd prefer sigh sound preferences over, being forced to use this new sigh sound, considering I prefer the Nova one heavily

2024-10-12 18:24 UTC, Hardly3D commented
Whoops, I'll get to this eventually, been a bit busy.

2024-10-12 18:37 UTC, Hardly3D commented on modular_nova/modules/emotes/code/emotes.dm
> -/datum/emote/living/sigh_exasperated
It does seem to be from TG which was why I removed it and moved it to *sigh itself. But after seeing the above comment I'll see about bringing the sigh back to the original state. Two separate emotes are better than having a whole character preference for it.

2024-10-14 16:10 UTC, Hardly3D commented
I've brought back Nova's *sigh, and moved the *esigh sound to TG's which should be about the exact same.

2024-10-15 20:22 UTC, GoldenAlpharex requested changes
I just wanted to say that I appreciate all of the time you've spent working on this, I know I haven't been reviewing this as quickly as I should have. Most of my comments here are to ensure consistency and proper change documentation, to ensure that we're all up-to-date with what's being changed here, and to make sure that the changes really bring what's desired out of them.

I hope this review doesn't come off as condescending, that's not the intention, I just had a few questions that I figured needed responded to first before we can move forward with this.

Also, it might be wise to double-check that the moth/insect scream merge doesn't break people's preferences if they were already using that one. If so, it might require a simple addition to the preferences migration script.

2024-10-15 20:22 UTC, GoldenAlpharex commented on modular_nova/modules/emotes/sound/emotes/clap1.ogg
The removal of clap sounds wasn't documented in the PR and no examples of what they sound like with the updated sounds were given.

2024-10-15 20:22 UTC, GoldenAlpharex commented on modular_nova/modules/emotes/code/emotes.dm
> +		return 'sound/mobs/humanoids/human/sigh/female_sigh.ogg'
Are those the same sounds as they were before, but just brought up to /tg/? Or is this just the same sound file that's used for regular sighs? The exasperated sigh having a different sound doesn't seem to be a bad thing to me, if this just removes its uniqueness, I don't think I'm really in favor of that change.

2024-10-15 20:22 UTC, GoldenAlpharex commented on modular_nova/modules/emotes/code/dna_screams.dm
> -		)
What happens for the default scream sounds, now, then?

2024-10-24 01:12 UTC, Hardly3D commented
I believe it might end up randomizing those who have the insect laugh, I'll look up on how to make it migrate to moth's

2024-12-09 06:51 UTC, Hardly3D commented
Stale begone
Still trying to see how I could make pref migration work by asking thru discord

2025-01-03 01:02 UTC, closed without merging