make able read paper from folder
NovaSector/NovaSector pull request #4446
Opened 2024-10-02 10:47 UTC by hack-wrench

## About The Pull Request

Improved due to the complexity of running a bureaucracy (I don't have enough GBP on TG for this QoL)

## How This Contributes To The Nova Sector Roleplay Experience

Conveniently store photos and papers in a folder without having to reach in and disorder them

## Changelog

:cl:
qol: make able reading the paper in the folder
/:cl:

2024-10-02 18:57 UTC, SomeRandomOwl requested changes

2024-10-02 18:57 UTC, SomeRandomOwl commented on code/modules/paperwork/paper.dm
> +	if(in_contents_of(/obj/machinery/door/airlock) || in_contents_of(/obj/item/clipboard) || in_contents_of(/obj/item/folder))
```suggestion
	if(in_contents_of(/obj/machinery/door/airlock) || in_contents_of(/obj/item/clipboard) || in_contents_of(/obj/item/folder)) // NOVA EDIT - ORIGINAL: if(in_contents_of(/obj/machinery/door/airlock) || in_contents_of(/obj/item/clipboard))
```

2024-10-03 05:16 UTC, OrionTheFox commented
This kind of small QoL should be upstreamed. Semi-modular code improvements should just be fully integrated upstream code improvements.

2024-10-04 05:13 UTC, hack-wrench commented
> This kind of small QoL should be upstreamed. Semi-modular code improvements should just be fully integrated upstream code improvements.

Upstream rejected QoL due to negative GBP

2024-10-05 00:22 UTC, merged

2024-10-05 19:47 UTC, hack-wrench commented
> Would you mind if I tried remaking your PR upstream to see if they'd take it? In the meantime I'm fine with this

No problem