a couple of emote changes
NovaSector/NovaSector pull request #4508
Opened 2024-10-19 18:37 UTC by Neocloudy

## About The Pull Request
- **the 5 second cooldown per emote is reverted for most emotes**
  - some emotes still have it (purr, wurble, bork, cackle, growl)
- felinid/taj meow/purr emotes now use the tg meow/purr sounds
  - no the oranges meow Cannot happen with this one
![image](https://github.com/user-attachments/assets/7604a3bc-d67a-42b7-bc1a-4db85d260503)

## How This Contributes To The Nova Sector Roleplay Experience
I feel like the 5 second cooldown wasn't really needed here in particular, and it's just really inconvenient :sob:

Also, the TG meow/purr sounds are a lot better than what we have. Both of our sounds for these were just really annoying

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

https://streamable.com/q6dtpd

</details>

## Changelog

:cl:
del: [NOVA] the 5 second cooldown per emote has been mostly reverted: now only the 2 second cooldown is applied. these emotes still have cooldowns: purr, bork, wurble, cackle, growl
sound: the felinid/taj meow and purr emotes use the tg meow and purr sounds
/:cl:

2024-10-20 00:19 UTC, GoldenAlpharex submitted a review, later dismissed

2024-10-20 00:19 UTC, GoldenAlpharex commented on modular_nova/master_files/code/datums/emotes.dm
> +	specific_emote_audio_cooldown = 0 SECONDS
I'm not against it being more adjusted to each sound, but having it be flat-out 0 means that people can *easily* spam them in order to create a LOT of noise spam for no reason. It's not an *if* it's going to happen, it *will* happen, there should still be some delay between the noises, and there should be a duration by default, for all of the people that might forget about it when adding their own sound emotes.

2024-10-20 01:06 UTC, Neocloudy commented on modular_nova/master_files/code/datums/emotes.dm
> +	specific_emote_audio_cooldown = 0 SECONDS
setting it to 0 seconds means only the two second cooldown for all successful emote sounds gets applied, so this is the original behavior before the recent mirrors

anyway- what do you think it should be set to?

2024-10-26 17:20 UTC, vinylspiders requested changes

2024-10-26 17:32 UTC, vinylspiders requested changes
Also, you'll now have to also override `specific_emote_audio_cooldown = 5 SECONDS` for the following TG emotes: 
`/datum/emote/living/carbon/clap`, 
`/datum/emote/living/sneeze`, 
`/datum/emote/living/cough/`, and
`/datum/emote/living/carbon/whistle` 

plus the (modular) `/datum/emote/living/clap`

because they relied on the default being `5 SECONDS`.

2024-10-26 18:33 UTC, vinylspiders approved these changes

2024-10-28 12:01 UTC, Sadboysuss commented
Removing the code that prevents audible emote spam on an hrp server so you can meow more often

2024-10-28 22:28 UTC, merged

2024-10-28 22:34 UTC, Hlscientist commented
The new meows are a bit too silent... could you make them a bit louder?