Adds new drinks and foods, giving starfruit functionality
NovaSector/NovaSector pull request #4580
Opened 2024-11-09 23:50 UTC by Draggeru

## About The Pull Request

What the tin says, branches off of #4505 by adding 7 new drinks and roughly 14 new dishes (I stopped counting).

Drinks:

Starfruit soda: starfruit juice 2, rum 2, cognac 1, soda water 1

Starfruit lubricant(Synth): starfruit juice 1, Synthanol 1

Starlit Latte: starfruit juice 1, coffee 1

Starbeam Shake: starfruit juice 1 , vanilla dream 1 , ice 1

Forgotten Star: starfruit juice 1, creme de coconut 1, white russian 1, pineapple juice 1, bitters 1

Astral Flame: Starfruit juice 1, navy rum 1, lime juice 1, soda water 1, menthol 1

Space Muse: starfruit juice 1, creme de menthe, 1 vodka

## How This Contributes To The Nova Sector Roleplay Experience

Giving a plant functionality when it costs 1 thousand credits to obtain is objectively good game design.

God help the changelog.

## Proof of Testing

Game compiles

![prdrinks](https://github.com/user-attachments/assets/adfd85b1-e08b-4276-bccb-8c567ce54a6c)

![prfoods](https://github.com/user-attachments/assets/ed274904-7a3e-469f-81f9-767958366feb)

## Changelog

:cl: Thedragmeme
add: Adds 7 new drinks: Starfruit Soda, Starfruit Lubricant(Synth), Starlit Latte, Starbeam Shake, Forgotten Star, Astral Flame, and Space Muse
add: Adds 14 new dishes: Glazed Ribs, BBQ Meat Platter, Chicken Alfredo(cursed), Starfruit Sushi Roll, Starfruit Sashimi, Starfruit Eggplant Stir Fry, Starfruit Tofu Beef Ramen, Starfruit Noodles, Starfruit Cake(do you see the theme yet), Starfruit Jelly, Starfruit Macaron, Starfruit Cobbler, Starfruit Jelly Toast, Starfruit Pie, Starfruit Compote, Starfruit Creme Brulee, and Starfruit Cupcake
image: Adds roughly 20 new sprites to the game
/:cl:

2024-11-09 23:52 UTC, Draggeru commented
God damnit it did the thing again

2024-11-09 23:55 UTC, Draggeru commented
I need to fix three dishes that don't want to be consumable for some reason, but otherwise the PR is ready

2024-11-10 00:13 UTC, GreytideSkye commented
Oooh, is the Starlight Latte a reference to the Starlight Brigade song? Nice!

2024-11-10 00:26 UTC, Draggeru commented
> Oooh, is the Starlight Latte a reference to the Starlight Brigade song? Nice!

Love me some TWRP

2024-11-10 06:02 UTC, CRITAWAKETS commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	nutriment_factor = 0
```suggestion
	nutriment_factor = 0
	quality = DRINK_VERYGOOD
```
you probably forgor this but right now this is the only one of the drinks that's Just Mediocre which is likely not intended

2024-11-10 06:17 UTC, CRITAWAKETS reviewed
There are a few foods that aren't subtypes without starting food reagents, which is likely what's causing some foods to be non-consumable.

Also starfruit pie might be lacking a crafting recipe.

2024-11-10 06:17 UTC, CRITAWAKETS commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	icon_state = "spacejamtoast"
```suggestion
	icon_state = "spacejamtoast"
	food_reagents = list(
		/datum/reagent/consumable/nutriment = 8,
		/datum/reagent/consumable/nutriment/vitamin = 4,
	)
```

2024-11-10 06:17 UTC, CRITAWAKETS commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +/obj/item/food/pie/starfruitpie
Is this meant to not have any recipe?

2024-11-10 06:17 UTC, CRITAWAKETS commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	icon_state = "compote"
```suggestion
	icon_state = "compote"
	food_reagents = list(
		/datum/reagent/consumable/nutriment = 12,
		/datum/reagent/consumable/nutriment/vitamin = 6,
	)
```

2024-11-10 06:17 UTC, CRITAWAKETS commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	icon_state = "cremebrulee"
```suggestion
	icon_state = "cremebrulee"
	food_reagents = list(
		/datum/reagent/consumable/nutriment = 6,
		/datum/reagent/consumable/nutriment/vitamin = 2,
	)
```

2024-11-10 06:21 UTC, Draggeru commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +/obj/item/food/pie/starfruitpie
No, fuck

2024-11-10 23:16 UTC, Draggeru commented
Bugs are fixed and the pie recipe was added, no further changes are anticipated and PR is ready for full review

2024-11-11 15:37 UTC, Draggeru commented
![Screenshot_20241111_093640_Chrome](https://github.com/user-attachments/assets/6931d736-2cdc-4829-ad04-4f5b298e16de)

Mom pick me up I'm scared

2024-11-15 03:20 UTC, Iamgoofball commented
This should all be upstreamed to /tg/ direct, nothing wrong with any of this

2024-11-15 03:33 UTC, Draggeru commented
> This should all be upstreamed to /tg/ direct, nothing wrong with any of this, sprites look good.
> 
> Starfruit should probably get some kind of gene for genemodding, though; It does cost 1000 credits, after all.

Starfruit was added as a donator item, I am open to discussing with Golden and Snailomi (whos donator slot was used) what exactly could be done with that donor slot but at current this PR gives functionality to what is in spirit a donator item for the server.

As for the food items themselves, I do not mind if they are added upstream with alternative recipes if a compromise for the starfruit is not reached.

On a side note if I have to stare at this code any more I might actually lose it, so any upstream would have to be done by someone else

2024-11-15 03:40 UTC, Iamgoofball commented
>this PR gives functionality to what is in spirit a donator item for the server.

This seed is available via the cargo bay already, that ship has sailed.

2024-11-15 03:43 UTC, Iamgoofball commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +/obj/item/book/manual/starfruit
This doesn't really need to exist; There's actually an in-game recipe searcher on chem dispensers(and booze/soda machines), it's accessible via the top of the dispenser in the little help icon.
![KamNcnzuuf](https://github.com/user-attachments/assets/baa94e40-c0e5-4d4f-a504-fd6a87f9c2b8)
![PAllzXubsA](https://github.com/user-attachments/assets/16fa6f73-4ca0-40b6-9d00-17d5728eb748)
![hm4xRxoyGi](https://github.com/user-attachments/assets/0292c682-c0cc-4467-8ba7-920ed9e30e3f)

2024-11-15 03:44 UTC, Draggeru commented
> > this PR gives functionality to what is in spirit a donator item for the server.
> 
> This seed is available via the cargo bay already, 

Due to the kindness of the donator, you should not ignore the fact the item is at its core is a donator item. I do not have any doubt that permission will be given but this should be handled appropriately.

2024-11-15 03:45 UTC, Iamgoofball commented
They really should not have approved a donator item of such a caliber, it sets a stupid precedent akin to that time holographic wheelchairs were approved as a donator item. Donator items should be restrained to clothing only, but c'est la vie.

2024-11-15 03:54 UTC, Draggeru commented
> They really should not have approved a donator item of such a caliber, it sets a stupid precedent akin to that time holographic wheelchairs were approved as a donator item; reasonable gameplay concepts should not be donator items, donator items are supposed to be personalized clothing specific to a character. 

The plant is from the characters home planet, I am not interested in arguing semantics over donator items as I have discussed this donator item in particular with Golden. If you want to argue semantics then speak to Golden.

2024-11-15 03:57 UTC, Draggeru commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +/obj/item/book/manual/starfruit
Boring.

2024-11-16 17:26 UTC, Zergspower commented
Donator item is fine, and we already have a gold wheelchair donator item so a hardlight one is also fine. From what i can tell the seed is only affecting loadout which is harmless, if something was approved as a dono item there's not much action to take after.

2024-11-20 02:41 UTC, CRITAWAKETS commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	name = "starfruit noddles"
```suggestion
	name = "starfruit noodles"
```
noddles

2024-11-20 02:50 UTC, CRITAWAKETS commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	desc = "A roll of simple vegetarian sushi with rice, carrots, and potatoes. Sliceable into pieces!"
```suggestion
	desc = "A roll of simple sushi with delicious starfruit sashimi. Sliceable into pieces!"
```
just outright wrong right now since its made of fish without carrot or potato. here's the desc from the upcoming maple port

2024-11-21 00:20 UTC, Draggeru commented
> This should all be upstreamed to /tg/ direct, nothing wrong with any of this, sprites look good.
> 
> Starfruit should probably get some kind of gene for genemodding, though; It does cost 1000 credits, after all.

Go off for an upstream merge bestie. I'm not doing it tho

2024-11-21 02:24 UTC, GoldenAlpharex commented on modular_nova/modules/cargo/code/packs.dm
> +		/obj/item/book/manual/starfruit =1,
```suggestion
		/obj/item/book/manual/starfruit = 1,
```

2024-11-21 02:35 UTC, GoldenAlpharex requested changes
Sorry for the late review, real life's been a bitch recently. The sprites are awesome as always, though!

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	required_reagents = list(/datum/reagent/consumable/starfruit_juice = 2, /datum/reagent/consumable/ethanol/rum = 2, /datum/reagent/consumable/ethanol/cognac = 1, /datum/reagent/consumable/sodawater =
Multi-line lists greatly help visibility, and are recommended for associative lists in general, as well as long lists.
```suggestion
	required_reagents = list(
		/datum/reagent/consumable/starfruit_juice = 2,
		/datum/reagent/consumable/ethanol/rum = 2,
		/datum/reagent/consumable/ethanol/cognac = 1,
		/datum/reagent/consumable/sodawater = 1,
	)
```

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	required_reagents = list(/datum/reagent/consumable/starfruit_juice = 1, /datum/reagent/consumable/ethanol/synthanol = 1)
```suggestion
	required_reagents = list(
		/datum/reagent/consumable/starfruit_juice = 1,
		/datum/reagent/consumable/ethanol/synthanol = 1,
	)
```

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	required_reagents = list(/datum/reagent/consumable/starfruit_juice = 1, /datum/reagent/consumable/coffee = 1)
```suggestion
	required_reagents = list(
		/datum/reagent/consumable/starfruit_juice = 1,
		/datum/reagent/consumable/coffee = 1,
	)
```

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	required_reagents = list(/datum/reagent/consumable/starfruit_juice = 1, /datum/reagent/consumable/ethanol/navy_rum = 1, /datum/reagent/consumable/menthol = 1, /datum/reagent/consumable/limejuice = 1
```suggestion
	required_reagents = list(
		/datum/reagent/consumable/starfruit_juice = 1,
		/datum/reagent/consumable/ethanol/navy_rum = 1,
		/datum/reagent/consumable/menthol = 1,
		/datum/reagent/consumable/limejuice = 1,
		/datum/reagent/consumable/sodawater = 1,
	)
```

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	required_reagents = list(/datum/reagent/consumable/starfruit_juice = 1, /datum/reagent/consumable/ethanol/creme_de_menthe = 1, /datum/reagent/consumable/ethanol/vodka = 1)
```suggestion
	required_reagents = list(
		/datum/reagent/consumable/starfruit_juice = 1,
		/datum/reagent/consumable/ethanol/creme_de_menthe = 1,
		/datum/reagent/consumable/ethanol/vodka = 1,
	)
```

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	name = "starfruit cake"
I won't go around capitalizing all of these, but- Basically, all reagents and crafting recipes should have their name capitalized on the datum. It's what shows up in the TGUI interfaces, and is standardized as each word of their name being capitalized.

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	name = "Starfruit Macaron"
Like this right here, this is exactly how to do it. The item itself isn't capitalized, but the crafting recipe is. Perfect.

2024-11-21 02:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	starting_content = {"<html>
Gosh, that's cursed, I kinda hate that, but I'm not going to be overly anal about it.

2024-11-21 17:31 UTC, Draggeru commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	starting_content = {"<html>
Authors get a little freaky at 3 am, I'll see about a less sleep deprived name

2024-11-21 21:34 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	required_reagents = list(/datum/reagent/consumable/starfruit_juice = 1, /datum/reagent/consumable/pineapplejuice = 1, /datum/reagent/consumable/ethanol/white_russian = 1, /datum/reagent/consumable/e
```suggestion
	required_reagents = list(
		/datum/reagent/consumable/starfruit_juice = 1,
		/datum/reagent/consumable/pineapplejuice = 1,
		/datum/reagent/consumable/ethanol/white_russian = 1,
		/datum/reagent/consumable/ethanol/creme_de_coconut = 1,
		/datum/reagent/consumable/ethanol/bitters = 1,
	)
```

2024-11-21 21:35 UTC, GoldenAlpharex commented on modular_nova/modules/customization/modules/hydroponics/grown/starfruit.dm
> +	starting_content = {"<html>
Oh, I didn't mean the name, it was actually just how it's formatted in the file itself, it's just rare to see strings formatted like this, it looks weird when surrounded by code, even if it's a very valid way of doing things.

2024-11-21 21:35 UTC, GoldenAlpharex approved these changes
Should be good to go now!

2024-11-22 17:09 UTC, merged