Bitrunning Easy mode
NovaSector/NovaSector pull request #4652
Opened 2024-12-02 19:39 UTC by OrbisAnima

## About The Pull Request

- Doubles the amount of points received per domain won
- Makes sassysauge pizza available on the pizza delivery pool
- Makes Bitrunning disks size small, instead of normal
- Makes the gondola domain give one Neurine/Manitol/Pax/CherryJelly pill to counter the effect of the forced ejection due to the change., as a patch until the issue is solved.

## How This Contributes To The Nova Sector Roleplay Experience

- 2x the points reduce the grind.
- More pizza selection is good.
- Bitrunning disks being small while allows for crazy bitrunning builds, also let people to just... have their disks in a belt or part of their inventory without having to balance their bitrunning and station life too much
- While not ideal, addressing the gondola domain problem makes it so bitrunners dont fall for a 30 minute trap until medbay gets the chemicals to solve the issue. There is no other way to get that pill. 

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/user-attachments/assets/1bd6d0c8-acd2-4434-a998-bc0d46a55b6f)

Currently available balance: 200 np
  
</details>

## Changelog

:cl:
balance: Bitrunning Domains now give double points
qol: Pizza Delivery for bitrunners now include the new Sausage pizza on their possible sponsors!
balance: Bitrunner disks are now small sized, from normal.
qol: Gondola Domain now gives a single mind healing pill until the transformation issue that forcibly ejects you is fixed upstream, this patch is temporal and will be removed once upstream has the issue fixed.
/:cl:

2024-12-02 20:21 UTC, Stalkeros2 reviewed
(Thank you GitHub mobile for turning singular comments into reviews.)

2024-12-02 20:21 UTC, Stalkeros2 commented on modular_nova/modules/bitrunning/code/flair.dm
> +		/obj/item/food/pizza/sassysage,
This better be a pizza box obviously, otherwise it looks bad and can get moldy.

2024-12-02 20:28 UTC, OrbisAnima commented on modular_nova/modules/bitrunning/code/flair.dm
> +		/obj/item/food/pizza/sassysage,
it is

2024-12-11 04:19 UTC, FlufflesTheDog requested changes

2024-12-11 04:19 UTC, FlufflesTheDog commented on code/modules/bitrunning/server/loot.dm
> +	SEND_SIGNAL(src, COMSIG_BITRUNNER_DOMAIN_COMPLETE, cache, generated_domain.reward_points*2) // NOVA EDIT CHANGE - Original : SEND_SIGNAL(src, COMSIG_BITRUNNER_DOMAIN_COMPLETE, cache, generated_domai
```suggestion
	SEND_SIGNAL(src, COMSIG_BITRUNNER_DOMAIN_COMPLETE, cache, generated_domain.reward_points * 2) // NOVA EDIT CHANGE - Original : SEND_SIGNAL(src, COMSIG_BITRUNNER_DOMAIN_COMPLETE, cache, generated_domain.reward_points)
```
gonna nitpick this

2024-12-11 04:19 UTC, FlufflesTheDog commented on code/modules/bitrunning/server/loot.dm
> +	points += (generated_domain.reward_points*2) // NOVA EDIT CHANGE - Original : points += generated_domain.reward_points
```suggestion
	points += (generated_domain.reward_points * 2) // NOVA EDIT CHANGE - Original : points += generated_domain.reward_points
```
same (I'm mad github won't let me do this in a single comment)

2024-12-11 04:19 UTC, FlufflesTheDog commented on modular_nova/modules/bitrunning/code/domain_additions.dm
> +	completion_loot = list(/obj/item/reagent_containers/pill/bitrunner_delight = 1) //This is just here as a patch over the current issue with gondola force ejecting you over transformation.
I don't think I'm a huge fan of this. There's a [fix](https://github.com/tgstation/tgstation/pull/88398) merged upstream now, just need to get that over here.

2024-12-11 06:25 UTC, FlufflesTheDog approved these changes

2024-12-11 06:25 UTC, merged