Add Neglected Mobs to Gold Slime Spawns
NovaSector/NovaSector pull request #4699
Opened 2024-12-21 22:50 UTC by LordHookie

## About The Pull Request

Adds some rarely-seen mobs that were left out of gold slime friendly and hostile pools into them.

Specifically adds:
Deer, Foxes, Gondolas and Dobermanns to the **Friendly** spawn pool,

Centaurs, Electric Mosquitoes, Piano Mimics, Flesh Spiders, Space Bats, Gelatinous Cubes, and Sholean Grapes to the **Hostile** spawn pool,

and removes the Lusty Xenomorph Maid from the hostile pool, as her sprite has been broken for quite a while. She is replaced with the equally weird spaceman basic mob.

## How This Contributes To The Nova Sector Roleplay Experience

Variety is good, and the gold slime pool is about 25% spiders. Adding some otherwise very uncommon (or in some cases essentially nonexistent) mobs to the pool will hopefully both give the reaction a little more variety in both mechanics and roleplay, improve roleplay opportunities for sentient mobs by having more creatures to work with, and also give mobs that most people will probably never even know exist a little more exposure, as well as dilute the spider/spider/viscerator hell that is looking for a mob that might be interesting to sentient.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>

  _Flesh Spider and Space Bat_
![image](https://github.com/user-attachments/assets/6cc0f8c8-62bc-4da1-b83e-1563463f3768)

_A derivative is used that is set to no ghost control, as the original grapes ooze is possessable by default_
![image](https://github.com/user-attachments/assets/baf91f61-5b07-43e0-9110-7d386d956f77)

</details>

## Changelog

:cl:
add: Xenobiologists are reporting an uptick of variety in the creatures coming from gold slime reactions, including some deep space creatures, common pets, and the remaining two creatures otherwise only seen accompanying molds.
fix: Gold slimes can no longer create an invisible Lusty Xenomorph Maid.
/:cl:

2024-12-21 22:54 UTC, GreytideSkye commented
Thoughts on Serenitystation's Megadeer as hostile? They're about on-par with two carp.  modular_nova/modules/serenitystation/code/mobs/megadeer/megadeer.dm

2024-12-21 22:54 UTC, LordHookie commented
Open to feedback. I avoided any of the blatantly supernatural or severely out of place mobs, and mostly focused on adding stuff to hopefully vary up the kind of stuff Xenobiologists can get themselves killed by a little.

At some point I should honestly consider reworking how gold slime reactions work, and maybe make them part of cytology a bit more? But that's a much larger project for when I understand the codebase much better than I do right now.

2024-12-21 22:59 UTC, LordHookie commented
> Thoughts on Serenitystation's Megadeer as hostile? They're about on-par with two carp. modular_nova/modules/serenitystation/code/mobs/megadeer/megadeer.dm

I tried to avoid any of the mining mobs, in part because they have the weird telegraphed melee strikes that make them feel rather out of place. Moreover, I don't want to just make it so Xenobiologists can gold slime their way into any mob they want to play with - I considered and decided against adding xenomorphs to the hostile mob list because it gives Xenobiologists something to either hunt for themselves or take the opportunity to toy with should they appear.

Megadeer can be found consistently enough that if a Xenobiologist wants to play with them, I think it's a fair ask for them to go and hunt one down and haul it back to their lab. Given, they don't spawn outside of Serenity, but the same could be said about the snow mining mobs for Icebox and Snowglobe.

2024-12-21 23:05 UTC, LordHookie commented
Oh, an error. Weird. Ran fine for me. Testing time.

2024-12-21 23:22 UTC, FlufflesTheDog requested changes
Be sure to check out the [guide to modularization](https://github.com/NovaSector/NovaSector/blob/master/modular_nova/readme.md), any edit to tg files (things outside of `modular_mova/`) need to be marked with comments indicating changes, or moved a modular file entirely.

2024-12-21 23:22 UTC, FlufflesTheDog commented on code/modules/mob/living/simple_animal/hostile/ooze.dm
> +
```suggestion
/mob/living/simple_animal/hostile/ooze/grapes/xenobio
	ghost_controllable = FALSE
	gold_core_spawnable = HOSTILE_SPAWN
```
When making an override, everything from the parent type (`/mob/living/simple_animal/hostile/ooze/grapes`) remains unmodified by default, so you only need to specify things with modifications. Helps with clarity, and with not needing to update things if something in the base type is changed.

This is also what's causing the test failure, you'll had to add this mob type to the list in `simple_animal_freeze.dm`, which exists to stop new simple_animals from being made (as they're being phased out in favor of basic mobs), but this just being an override of an existing one should be fine.

2024-12-21 23:31 UTC, LordHookie commented
> Be sure to check out the [guide to modularization](https://github.com/NovaSector/NovaSector/blob/master/modular_nova/readme.md), any edit to tg files (things outside of `modular_mova/`) need to be marked with comments indicating changes, or moved a modular file entirely.

Right, forgot "modular_nova" and just the "modules" folder aren't the same. I hate file structure sometimes. Gimme a few hours.

2024-12-22 01:04 UTC, LordHookie commented
Having a bit of trouble with the modular code not working.

```
/mob/living/basic/flesh_spider
	gold_core_spawnable = HOSTILE_SPAWN
```

_should_ do it, right? it seems to work for `modular_creature`, but it isn't working here. flesh spiders remain unspawnable

2024-12-22 02:04 UTC, LordHookie commented
Figured out what i forgot. First time having to modularize something, can you tell?
Anyway, should work now, sorry for the holdup. Will let the checks run through and then mark as ready if they pass.

2024-12-22 02:35 UTC, LordHookie commented
First try. I _think_ I modularized it correctly, there's only a core file edit where there _**must**_ be to make the auto-checker calm down. LMK

2024-12-22 07:42 UTC, FlufflesTheDog reviewed
Looks a lot better. Do you know if the drops from these might be particularly abusable? I know gondola hide at least is pretty expensive but I'm not sure how spammable these extracts are either

2024-12-22 07:42 UTC, FlufflesTheDog commented on modular_nova/modules/more_gold_slime_monsters/code/more_gold_slime_monsters.dm
> +
```suggestion
```
Not a fan of workarounds like this since it relies on someone remembering & bothering to come back once it is working, it just serves to shove problems under the rug so to speak

2024-12-22 07:42 UTC, FlufflesTheDog commented on modular_nova/modules/more_gold_slime_monsters/code/more_gold_slime_monsters.dm
> +// other two mobs i changed are already modular
```suggestion
```
nitpicking but
This is only really relevant in terms of this particular PR, doesn't really add anything to the code

2024-12-22 15:29 UTC, LordHookie commented on modular_nova/modules/more_gold_slime_monsters/code/more_gold_slime_monsters.dm
> +// other two mobs i changed are already modular
ok

2024-12-22 15:33 UTC, LordHookie commented
> Looks a lot better. Do you know if the drops from these might be particularly abusable? I know gondola hide at least is pretty expensive but I'm not sure how spammable these extracts are either

Gondola hide sells really well, but gold slime extracts only spawn a single thing, and nobody ever uses their water reaction. You'd need a decent amount of effort to get a large number of gondola hides, or at least spend most of your shift waiting on a metal extract to synthesize more of them.

I could put them under hostile_spawn if spam is a concern, since that'll **massively** dilute being able to spawn them consistently, which would make this way harder to get access to.

None of the other mobs have meaningful drops at all. Meat and hide when butchered, otherwise nada, the usual.

2024-12-22 15:38 UTC, LordHookie commented on modular_nova/modules/more_gold_slime_monsters/code/more_gold_slime_monsters.dm
> +
I mean, I could put it back, but what does that serve? It's an upstream mob that's, inexplicably, broken. While sure, **we** _could_ leave it in the hope that somebody just fixes it, the fact it's been here so long I think indicates that nobody knows why it's broken or how to fix it.

And looking at the code, I don't either! It should by all means be working perfectly. I figure it's better to remove it from the pool until it's figured out than leave a blatant bug in the game in hope of a fix that probably isn't coming, at least not anytime soon.

2024-12-22 20:24 UTC, FlufflesTheDog commented on modular_nova/modules/more_gold_slime_monsters/code/more_gold_slime_monsters.dm
> +
https://github.com/NovaSector/NovaSector/pull/4702
There's always a reason, and making them not spawn from *this* is not a fix because they can still spawn from other sources

2024-12-23 01:05 UTC, LordHookie commented on modular_nova/modules/more_gold_slime_monsters/code/more_gold_slime_monsters.dm
> +
In the process of trying to prove the point that the Xenomorph maid does have an icon state, I actually realized what the problem is. We overwrite the file for the alien icons to `'modular_nova/master_files/icons/mob/big_xenos.dmi'` in a module.

This applies to the maid as well, but the maid does not _have_ a state in big_xenos.dmi. I'm just going to tell the maid to go back to using the old sprite for her. I can split into a separate PR if you'd like.

2024-12-23 01:13 UTC, LordHookie commented on modular_nova/modules/more_gold_slime_monsters/code/more_gold_slime_monsters.dm
> +
Well, seems like we've got this handled elsewhere. Woo, bugfixes.

2024-12-23 01:15 UTC, LordHookie commented
Moved Gondolas into HOSTILE_SPAWN to make them obtainable but rare, like lightgeists or fungu. Should be done now, unless you've got anything else.

2024-12-23 20:14 UTC, FlufflesTheDog approved these changes

2024-12-23 20:14 UTC, merged