[MODULAR] Back Items Tab for Loadout + Roundstart MODsuits
NovaSector/NovaSector pull request #759
Opened 2024-02-03 08:55 UTC by W4rd3nn

## About The Pull Request
You can pretty much customize every slot on your character through the loadout save for your back slot. This has worked for a while, but considering we're attempting to emulate round-to-round persistence more and more, and with the availability of modsuits through the entombed quirk, I believe we should be able to start with a few different back items via the loadout.

Namely, back items currently appear in three categories

**Back storage**, which includes a number of special backpacks including smuggler satchels, bunny satchels, CIN packs, and more. Each backpack has been tested to ensure it does not provide any advantage outside a handful being fireproof and one, the smuggler satchel, can fit under floor tiles. Most back items have been restricted from the prisoner role as well, save for some civilian-like ones and the smuggler satchel, since it's thematic for prisoners to have a method of smuggling and hiding contraband. Additionally, the gravity harness is added here by recommendation. This includes job specific backpacks, which includes every commonly available departmental backpack with the addition of being available to everyone (excluding prisoners). I assume most people would keep their backpack and not wear a new one if they happen to be off-duty one day, so this provides that option to them. Your seccie signing on as off-duty? Feel free to use the same backpack! Also some job backpacks (industrial and explorer) are drippy as hell and it's a shame they're locked behind those roles.

**Non-storage items**, which at the moment only includes three different colors of oxygen tank. This will likely be expanded in the future.

**MODsuits**, likely the most controversial aspect of this PR, but really with the high-tech setting we're trying to emulate, we really should let people start the round with a modsuit. The modsuits are separated into two groups. 

Civilian mods are available for everyone (excluding prisoners), but are heavily nerfed from their normal variants. These are primarily meant to be cosmetic and are all based off the "standard" pre-equipped mod. These only start with three modules. Standard storage, a status readout, and an emergency tether.

Job mods are only available for their respective roles. There's really no reason to have to fight over the few mods in your department, especially since most people end up ordering more anyways. These are unchanged from their typical configuration. Head-specific mods will NOT be made available, as their status should not be compromised by having multiple copies in a single round.

Due to how the loadout system works, these back items work **best** with the "place all in case" option, as the backpack will get overridden otherwise. Modsuits seem to work with "place job in backpack" for some reason, though.

## How This Contributes To The Nova Sector Roleplay Experience
We should allow a great degree of player customization and minimize engaging with mechanics to acquire cosmetic items. Additionally, since modsuits are now available via the entombed quirk, it makes sense to also allow people to use them via the loadout.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  
![image](https://github.com/NovaSector/NovaSector/assets/12723348/95d24bd6-57a7-4603-bdd6-2a21b2eaba52)

https://github.com/NovaSector/NovaSector/assets/12723348/0b6d02e3-3dab-4de7-b896-719076adad09

</details>

## Changelog

:cl:Motho
add: Back items, including certain MODsuits, are now available in the Loadout.
/:cl:

2024-02-03 08:56 UTC, Stalkeros2 commented
Finally.

2024-02-03 09:16 UTC, Manfred21 commented
For my part, I feel that roundstart MODs don't present a significant balance issue because by the time a MOD is probably required, anyone who might affect the balance of the round likely either has one, has access to one, or has access to a better one than the loadout variants. Plus, it only makes sense that a setting with portable, deployable backpacks would probably have them accessible to your average stationgoer.

2024-02-03 14:32 UTC, Stalkeros2 commented on modular_nova/modules/loadouts/loadout_items/loadout_datum_back.dm
> +	item_path = /obj/item/storage/backpack/nri
Please get rid of this ancient sprite backpack; CIN ones are better.

2024-02-03 15:38 UTC, nikothedude commented
the mods shouldnt be in there for reason of availability

med starts with ONE modsuit.
cargo starts with ONE modsuit.
sec starts with TWO modsuits.
atmos starts with TWO modsuits.

i agree with burger, youre overlooking the reasons for why these things are limited to begin with

theres also the question of why youre giving CLOWNS modsuits? and just giving EVERYONE _constant_ EVA ability? EVA is limited for a reason

2024-02-03 15:40 UTC, nikothedude commented on modular_nova/modules/loadouts/loadout_items/loadout_datum_back.dm
> +/datum/loadout_item/back/smuggler
a flat NO. smuggler stachels are more than just "oh we can put them under tiles".

they fit in other bags, and hold FIFTEEN ITEMS. they are QUITE POWERFUL and theres a reason theyre so desired on places like TG, its because with one you can easily bypass storage restrictions

2024-02-03 15:41 UTC, nikothedude commented
also, entombed is a lot different because you literally c annot take the modsuit off, which is a fair tradeoff

2024-02-03 17:03 UTC, SomeRandomOwl commented
I agree with everyone above, roundstart modsuits is a bit too much here

2024-02-03 18:09 UTC, W4rd3nn commented
I'm open to nerfing the civilian grade MODs. Right now they're all the same as the general standard variant, which means little to no armor, 15 complexity, and a minorly alleviated slowdown. I can edit the themes to make them even less power. lower complexity, no armor, etc. I can even make them not pressureproof. I'm also open to removing the job specific suits altogether.

2024-02-03 20:09 UTC, Iamgoofball commented on modular_nova/modules/loadouts/loadout_items/loadout_datum_back.dm
> +	name = "Frontier Messenger Bag"
Please remove these and just make it respect the character preference for spawning with a satchel/duffel/messenger/normal bag.

2024-02-03 20:57 UTC, AdamElTablawy commented
> I'm open to nerfing the civilian grade MODs. Right now they're all the same as the general standard variant, which means little to no armor, 15 complexity, and a minorly alleviated slowdown. I can edit the themes to make them even less power. lower complexity, no armor, etc. I can even make them not pressureproof. I'm also open to removing the job specific suits altogether.

The armor is fine, but they shouldn’t be pressure proof and should have no removable parts/upgradeable parts.

No JOBmods other than engineering mods, preferably, either. Robotics should have some work or they’ll die of agony.

2024-02-03 21:23 UTC, Exo-212 commented
If any modsuit is added for everyone, the frontier modsuit with the plate compression seems like a good choice; it has no storage capability and the plate compression cannot be removed.

Furthermore, it's supposed to be outdated surplus with very low available complexity. 

Very happy about the backpacks though.

Finally, the drip never stops.

2024-02-05 00:37 UTC, chemistrymain2 commented
> just, dont allow modsuits roundstart, robotics can already make civ mods roundstart. dont needlessly nerf modsuits

the roundstart modsuit in this loadout option woul dbe weakened, not all mods

2024-02-05 08:18 UTC, kittysmooch commented
> > I'm open to nerfing the civilian grade MODs. Right now they're all the same as the general standard variant, which means little to no armor, 15 complexity, and a minorly alleviated slowdown. I can edit the themes to make them even less power. lower complexity, no armor, etc. I can even make them not pressureproof. I'm also open to removing the job specific suits altogether.
> 
> The armor is fine, but they shouldn’t be pressure proof and should have no removable parts/upgradeable parts.
> 
> No JOBmods other than engineering mods, preferably, either. Robotics should have some work or they’ll die of agony.

??? every robo main hates doing modsuits

2024-02-05 16:22 UTC, SomeRandomOwl commented
Taking away from a job is not what we need, we shouldent be taking away from robotics needing to make modsuits. We should be adding content that enhances jobs and not just makes things more convenient for some people while taking away from a job.

2024-02-06 01:41 UTC, Nerev4r commented
> Contributor

Robotics would still need to do the modules, which is fine w/ me

2024-02-07 03:33 UTC, radarseas commented
roundstart modsuits are a bad, bad idea... I don't think giving everyone the ability to have a modsuit without interacting with robotics and their limited cores and resources for them is a good idea _especally when cargo can buy all the good shit modules like expanded storage for like **barely 100 credits**._

Smuggler's satchels SOUND cool but... again, they hold a lot, of items, fit under tiles and fit into a backpack compactly.. its guarrenteed to be taken to powergame more than it is to add to the game...

Ghost roles don't have joblocks, department modsuits is a bad idea.

What goof said, I'd like to not have to scroll through a hundred varients of messager/duffle/satchel/backpack... else that's _four varients of every single, bag that's on the back slot_ thingy causing huge menu bloat, **we already have enough bloat in suit slots.**

2024-02-07 14:57 UTC, FieryMorty commented
I like the idea of having more variety, bare MODs available immediately, lots of different colors to choose from for tanks and bags. Please go forward with this!

2024-02-09 08:30 UTC, GlaciaImca commented
Its the pressure proof that makes me not want round-start mods, for synths this means you are space capable literally the second the round starts with absolutely zero preparation.... it also pretty much nullifies atmospherics as a danger....

2024-02-12 20:22 UTC, CandleJaxx commented
> Its the pressure proof that makes me not want round-start mods, for synths this means you are space capable literally the second the round starts with absolutely zero preparation.... just grab the mini fire extinguisher as a jetpack... it also pretty much nullifies atmospherics as a danger....

eh, pressure proof is overrated imo. plasmamen can be fully space worthy with a bin of papers and a fire suit.

2024-02-14 21:08 UTC, radarseas commented
the only concerns of roundstart modsuits to me is ions + bluespace cell (longer than a jetpack/extingisher) plus the spaceworthiness.

that and its also a biosuit in terms of viral protection (including thick material that **blocks syringe darts**. _you literally cannot get sick from a contact virus if your internals are on._


If we had a sane modsuit system like TG that didn't let you have online fully-retracted modsuits to negate the speed penalty almost entirely at no bootup time risk , this would be far less of an issue. (civilian modsuits basically have no slowdown).

2024-02-25 16:21 UTC, SomeRandomOwl requested changes
I discussed with the @vinylspiders about this and we would like the roundstart modsuits portion to be removed.

2024-02-26 04:25 UTC, W4rd3nn commented
I forgot this was still open. I've lost the enthusiasm to continue this PR. I may return to it at a later date, and others are free to pick up where I left off, but I'm not gonna be working on it any time soon. Sorry!

2024-02-26 04:25 UTC, closed without merging